// WEDJAT BRAIN V2 — General Knowledge Seed
//
// A broad, factually accurate general-knowledge base used to seed the Brain's
// KnowledgeItem store so that the Brain can answer common factual questions
// (capitals, basic science, math, history, technology, etc.) directly from
// retrieval without needing a web search on every turn.
//
// Each item is a self-contained, retrievable claim (good for semantic +
// keyword hybrid retrieval) with a fuller 1–3 sentence explanation. Items are
// grouped by `category` for easy auditing.

import { db } from "@/lib/db";
import { buildTermVector, serializeVector } from "./vectors";

export interface KnowledgeSeedItem {
  type: "FACT" | "RULE" | "PROCEDURE" | "OBSERVATION";
  claim: string;
  content: string;
  scope?: "APPLICATION" | "GLOBAL";
  evidence?: Array<{ evidenceType: string; content: string; section?: string }>;
  category: string;
  validFrom?: Date;
}

export interface KnowledgeSeedSource {
  sourceType: string;
  title: string;
  author: string;
  trustLevel: string;
  verificationStatus: string;
  dataClassification: string;
}

export const GENERAL_KNOWLEDGE_SOURCE: KnowledgeSeedSource = {
  sourceType: "web",
  title: "General Knowledge Base",
  author: "Wedjat Brain",
  trustLevel: "SUPPORTED",
  verificationStatus: "VERIFIED",
  dataClassification: "PUBLIC",
};

export const GENERAL_KNOWLEDGE_BASE: KnowledgeSeedItem[] = [
  // ===== GEOGRAPHY (35) =====
  { type: "FACT", category: "geography", claim: "The capital of France is Paris.", content: "Paris is the capital and most populous city of France, located on the Seine River in the north-central part of the country.", scope: "GLOBAL", evidence: [{ evidenceType: "citation", content: "Common geographic reference" }] },
  { type: "FACT", category: "geography", claim: "The capital of Japan is Tokyo.", content: "Tokyo is the capital of Japan and one of the most populous metropolitan areas in the world, located on the eastern coast of Honshu island.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Egypt is Cairo.", content: "Cairo is the capital of Egypt and the largest city in the Arab world, situated near the Nile Delta and the Great Pyramids of Giza.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of the United States is Washington, D.C.", content: "Washington, D.C. is the federal capital of the United States, a separate district on the Potomac River between Maryland and Virginia.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of the United Kingdom is London.", content: "London is the capital of the United Kingdom, located on the River Thames, and is a major global financial and cultural center.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Germany is Berlin.", content: "Berlin is the capital and largest city of Germany, located in the northeastern part of the country.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of India is New Delhi.", content: "New Delhi is the capital of India, an urban district within the larger Delhi metropolitan area in the north of the country.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of China is Beijing.", content: "Beijing is the capital of China, located in the north of the country and home to the Forbidden City and many national government institutions.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Brazil is Brasília.", content: "Brasília is the federal capital of Brazil, a planned city inaugurated in 1960 and located in the interior of the country.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Russia is Moscow.", content: "Moscow is the capital and largest city of Russia, located on the Moskva River in the western part of the country.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Canada is Ottawa.", content: "Ottawa is the capital of Canada, located in the province of Ontario along the Ottawa River, chosen as a compromise between English and French Canada.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Australia is Canberra.", content: "Canberra is the capital of Australia, a planned city located between Sydney and Melbourne, chosen as a compromise capital in 1908.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Saudi Arabia is Riyadh.", content: "Riyadh is the capital and largest city of Saudi Arabia, located in the center of the Arabian Peninsula.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of the United Arab Emirates is Abu Dhabi.", content: "Abu Dhabi is the federal capital of the United Arab Emirates, located on an island in the Persian Gulf and the largest emirate by area.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Turkey is Ankara.", content: "Ankara is the capital of Turkey, located in the central Anatolia region, while Istanbul remains its largest city.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Italy is Rome.", content: "Rome is the capital of Italy, located in the central-western part of the country on the Tiber River, and was the heart of the Roman Empire.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Spain is Madrid.", content: "Madrid is the capital and largest city of Spain, located in the center of the Iberian Peninsula.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Greece is Athens.", content: "Athens is the capital of Greece, one of the oldest cities in the world and the cradle of Western civilization and democracy.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Mexico is Mexico City.", content: "Mexico City is the capital of Mexico, a high-altitude metropolis built on the ruins of the Aztec capital Tenochtitlán.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of South Korea is Seoul.", content: "Seoul is the capital of South Korea, a major global metropolis located in the northwest of the country along the Han River.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Argentina is Buenos Aires.", content: "Buenos Aires is the capital of Argentina, located on the western shore of the Río de la Plata estuary in the east of the country.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The administrative capital of South Africa is Pretoria.", content: "South Africa has three capitals: Pretoria (executive), Cape Town (legislative), and Bloemfontein (judicial). Pretoria hosts most government departments.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Iran is Tehran.", content: "Tehran is the capital of Iran, located at the foot of the Alborz mountains in the north of the country.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Thailand is Bangkok.", content: "Bangkok is the capital and largest city of Thailand, located in the Chao Phraya River delta in the center of the country.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Indonesia is Jakarta.", content: "Jakarta is the capital of Indonesia, located on the northwest coast of Java island, and is among the most populous urban agglomerations in the world.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Nigeria is Abuja.", content: "Abuja is the capital of Nigeria, a planned city in the center of the country that replaced Lagos as capital in 1991.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Kenya is Nairobi.", content: "Nairobi is the capital of Kenya, located in the south-central part of the country, and hosts the headquarters of many UN agencies.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Sweden is Stockholm.", content: "Stockholm is the capital of Sweden, spread across 14 islands on the Baltic Sea coast and connected by more than 50 bridges.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Norway is Oslo.", content: "Oslo is the capital of Norway, located at the head of the Oslofjord in the southeast of the country.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of the Netherlands is Amsterdam.", content: "Amsterdam is the constitutional capital of the Netherlands, though the national government and parliament sit in The Hague.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Portugal is Lisbon.", content: "Lisbon is the capital of Portugal, located on the Atlantic coast at the mouth of the Tagus River, and is one of the oldest cities in Western Europe.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The capital of Switzerland is Bern.", content: "Bern is the de facto federal capital of Switzerland (referred to as the federal city), located on the Aare River in the west-central part of the country.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "There are seven continents on Earth: Africa, Antarctica, Asia, Australia (Oceania), Europe, North America, and South America.", content: "Asia is the largest continent by both area and population, while Antarctica is the coldest, driest, and least populated.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The Pacific Ocean is the largest and deepest ocean on Earth.", content: "The Pacific Ocean covers about 165 million square kilometers, larger than all of Earth's land area combined, and contains the Mariana Trench, the deepest point on Earth.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The Nile is generally considered the longest river in the world at about 6,650 km.", content: "The Nile flows northward through 11 countries in northeastern Africa and empties into the Mediterranean Sea. The Amazon is a close rival and carries far more water.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The Amazon River is the largest river in the world by water volume.", content: "The Amazon carries more water than the next seven largest rivers combined and drains the Amazon rainforest, the largest tropical rainforest on Earth.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "Mount Everest is the highest mountain on Earth at 8,849 meters (29,032 feet).", content: "Mount Everest sits on the border of Nepal and the Tibet Autonomous Region of China, in the Himalaya range.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The Sahara is the largest hot desert in the world.", content: "The Sahara covers about 9 million square kilometers across North Africa. The Antarctic Desert is the largest desert overall, since a desert is defined by low precipitation rather than heat.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "Russia is the largest country in the world by area.", content: "Russia spans about 17 million square kilometers across eastern Europe and northern Asia, covering more than one-eighth of Earth's inhabited land area.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "India is the most populous country in the world as of 2023.", content: "India surpassed China to become the most populous country with over 1.4 billion people, according to United Nations estimates.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "There are five oceans on Earth: Pacific, Atlantic, Indian, Southern, and Arctic.", content: "The Southern Ocean was formally recognized by the International Hydrographic Organization in 2000 and surrounds Antarctica.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "K2 is the second-highest mountain on Earth at 8,611 meters (28,251 feet).", content: "K2 sits on the China-Pakistan border in the Karakoram range and is considered more difficult to climb than Everest.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "Mount Kilimanjaro is the highest mountain in Africa at about 5,895 meters.", content: "Mount Kilimanjaro is a dormant volcano in northeastern Tanzania and the highest free-standing mountain in the world.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The Yangtze is the longest river in Asia at about 6,300 km.", content: "The Yangtze (Chang Jiang) flows entirely within China, from the glaciers of the Tibetan Plateau eastward to the East China Sea near Shanghai.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The Mississippi River is one of the longest rivers in North America at about 3,770 km.", content: "The Mississippi flows from northern Minnesota south to the Gulf of Mexico and, with the Missouri River as its main tributary, forms the largest river system in North America.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The Ganges is the most sacred river in Hinduism and flows through northern India and Bangladesh.", content: "The Ganges (Ganga) is about 2,525 km long, rising in the western Himalayas and emptying into the Bay of Bengal.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The Gobi is a large cold desert in northern China and southern Mongolia.", content: "The Gobi is the sixth-largest desert in the world at about 1.3 million square kilometers and is notable for its extreme temperature swings.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "The Kalahari is a semi-arid sandy desert covering much of Botswana and parts of Namibia and South Africa.", content: "The Kalahari covers about 900,000 square kilometers and supports more vegetation and wildlife than a true desert, hence being technically semi-arid.", scope: "GLOBAL" },
  { type: "FACT", category: "geography", claim: "Mont Blanc is the highest mountain in Western Europe at about 4,808 meters.", content: "Mont Blanc (White Mountain) sits in the French Alps near the Italian border and is the highest peak in the Alps range.", scope: "GLOBAL" },

  // ===== SCIENCE (32) =====
  { type: "FACT", category: "science", claim: "The speed of light in a vacuum is exactly 299,792,458 meters per second.", content: "The speed of light in vacuum (c) is a fundamental physical constant. Nothing carrying information can travel faster than c.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "The speed of sound in air at 20°C is approximately 343 meters per second.", content: "The speed of sound depends on the medium and temperature; it is much faster in water (about 1,480 m/s) and steel (about 5,000 m/s) than in air.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Standard gravitational acceleration at Earth's surface is approximately 9.8 m/s².", content: "Gravitational acceleration (g) varies slightly by latitude and altitude but is conventionally standardized at 9.80665 m/s².", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Avogadro's number is approximately 6.022 × 10²³ particles per mole.", content: "Avogadro's number is the number of atoms, molecules, or other elementary entities in one mole of a substance and is a foundational constant in chemistry.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "The Planck constant is approximately 6.626 × 10⁻³⁴ joule-seconds.", content: "The Planck constant (h) relates the energy of a photon to its frequency and is the cornerstone of quantum mechanics.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Water boils at 100°C (212°F) at standard sea-level atmospheric pressure.", content: "The boiling point of water decreases with altitude because atmospheric pressure is lower. On Mount Everest, water boils at about 68°C.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Water freezes at 0°C (32°F) at standard atmospheric pressure.", content: "When water freezes it expands, which is why ice floats on liquid water — an unusual property shared by very few substances.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "The adult human body has 206 bones.", content: "Humans are born with about 270 cartilaginous bones that fuse over time, leaving 206 distinct bones in a typical adult skeleton.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "An adult human has about 5 liters of blood circulating in the body.", content: "Blood volume averages about 5 liters in adult males and 4.5 liters in adult females, composed roughly 45% cells and 55% plasma.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "A normal resting heart rate for adults is 60 to 100 beats per minute.", content: "Resting heart rate varies with age, fitness, and health; well-trained athletes may have resting rates as low as 40–50 bpm.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "DNA has a double-helix structure.", content: "Deoxyribonucleic acid (DNA) consists of two strands wound around each other, with the genetic code spelled out by four bases: adenine, thymine, guanine, and cytosine.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Humans have 46 chromosomes (23 pairs) in each somatic cell.", content: "Twenty-two pairs are autosomes and one pair is sex chromosomes (XX for females, XY for males).", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Photosynthesis converts carbon dioxide and water into glucose and oxygen using sunlight.", content: "The simplified photosynthesis equation is: 6 CO₂ + 6 H₂O + light energy → C₆H₁₂O₆ (glucose) + 6 O₂. This process powers nearly all life on Earth.", scope: "GLOBAL" },
  { type: "RULE", category: "science", claim: "Newton's first law of motion states that an object at rest stays at rest and an object in motion stays in motion unless acted on by an external force.", content: "This is the law of inertia: objects resist changes to their state of motion. The resistance is proportional to mass.", scope: "GLOBAL" },
  { type: "RULE", category: "science", claim: "Newton's second law of motion states that force equals mass times acceleration (F = m·a).", content: "The net force on an object equals the product of its mass and the acceleration produced. Acceleration is in the direction of the net force.", scope: "GLOBAL" },
  { type: "RULE", category: "science", claim: "Newton's third law of motion states that for every action there is an equal and opposite reaction.", content: "If object A exerts a force on object B, then B exerts an equal and opposite force on A. The forces act on different bodies.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Hydrogen (H) is the most abundant chemical element in the universe.", content: "Hydrogen makes up about 75% of the universe's normal (baryonic) matter by mass and is the primary fuel of stars.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Oxygen (O) is the most abundant element in Earth's crust by mass.", content: "Oxygen makes up about 46% of Earth's crust by mass and is the third most abundant element in the universe after hydrogen and helium.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Carbon (C) is the chemical basis of all known life.", content: "Carbon's ability to form four stable covalent bonds allows the vast diversity of organic molecules that make up living organisms.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Iron (Fe) is the most abundant element in Earth's core and the fourth most abundant in Earth's crust.", content: "Iron is the main component of Earth's inner and outer core and is responsible for generating the planet's magnetic field through motion in the liquid outer core.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Gold (Au) is a dense, soft, yellow metal that is highly unreactive.", content: "Gold's chemical symbol Au comes from the Latin aurum. Because it barely tarnishes or corrodes it has been valued for ornament and coinage for thousands of years.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Silver (Ag) is the best electrical and thermal conductor of all metals.", content: "Silver's chemical symbol Ag comes from the Latin argentum. Its conductivity makes it valuable in electronics despite being more expensive than copper.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Copper (Cu) is a reddish, highly conductive metal used widely in electrical wiring.", content: "Copper's chemical symbol Cu comes from the Latin cuprum. It is the second-best conductor among common metals and far cheaper than silver.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "The pH scale measures acidity and alkalinity from 0 to 14.", content: "A pH of 7 is neutral, below 7 is acidic, and above 7 is basic (alkaline). The scale is logarithmic: each unit change represents a tenfold change in hydrogen ion concentration.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Pure water has a pH of 7, which is neutral.", content: "At 25°C, pure water has equal concentrations of H⁺ and OH⁻ ions, making it neither acidic nor basic. Most natural water is slightly acidic due to dissolved CO₂.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "There are four fundamental states of matter: solid, liquid, gas, and plasma.", content: "Solids hold a fixed shape and volume; liquids have fixed volume but flow; gases fill their container; plasma is an ionized gas found in stars and lightning.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "An atom consists of a nucleus (protons and neutrons) surrounded by electrons.", content: "Protons carry positive charge, neutrons are neutral, and electrons carry negative charge. The number of protons (atomic number) defines the element.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Water has the chemical formula H₂O, meaning each molecule has two hydrogen atoms and one oxygen atom.", content: "The bent shape of the water molecule and its polar O–H bonds give water its strong hydrogen bonding, high boiling point, and excellent solvent properties.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Common table salt has the chemical formula NaCl (sodium chloride).", content: "NaCl is an ionic compound formed when sodium (Na) donates an electron to chlorine (Cl). In water it dissociates into Na⁺ and Cl⁻ ions.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Carbon dioxide has the chemical formula CO₂.", content: "CO₂ is a colorless gas produced by respiration and combustion. It is a greenhouse gas and the primary carbon source for photosynthesis.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Earth's atmosphere is about 78% nitrogen and 21% oxygen by volume.", content: "The remaining 1% includes argon, carbon dioxide, water vapor, and trace gases. This composition is the result of billions of years of biological and geological activity.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "Cellular respiration converts glucose and oxygen into carbon dioxide, water, and usable energy (ATP).", content: "The simplified equation is: C₆H₁₂O₆ + 6 O₂ → 6 CO₂ + 6 H₂O + ATP. It is essentially the reverse of photosynthesis and powers most living cells.", scope: "GLOBAL" },
  { type: "FACT", category: "science", claim: "The human body is approximately 60% water by weight.", content: "Water percentage varies by age, sex, and body composition: brain and blood are about 70–85% water, while adipose tissue contains much less.", scope: "GLOBAL" },

  // ===== MATH (22) =====
  { type: "FACT", category: "math", claim: "Pi (π) is approximately 3.14159.", content: "Pi is the ratio of a circle's circumference to its diameter. It is irrational (cannot be expressed as a fraction) and transcendental (never terminates or repeats in any base).", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "Euler's number (e) is approximately 2.71828.", content: "e is the base of the natural logarithm and arises in continuously compounded growth, radioactive decay, and probability. Like π, e is irrational and transcendental.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The golden ratio (φ) is approximately 1.618.", content: "The golden ratio satisfies φ = (1 + √5)/2 and appears frequently in art, architecture, and nature where two quantities are in the same ratio as their sum is to the larger one.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The Pythagorean theorem states that in a right triangle, a² + b² = c².", content: "Here c is the hypotenuse (the side opposite the right angle) and a and b are the other two sides. It only applies to right triangles in a flat (Euclidean) plane.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The area of a circle is π·r², where r is the radius.", content: "If you know the diameter d instead, the area is π·(d/2)². Doubling the radius quadruples the area.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The circumference of a circle is 2·π·r (or π·d), where r is the radius and d is the diameter.", content: "The diameter is twice the radius (d = 2r), which is why the two formulas are equivalent.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The area of a rectangle is length × width.", content: "For example, a 4 m by 5 m rectangle has area 20 m². This is the basis for measuring the area of any flat shape.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The area of a triangle is ½ · base · height.", content: "Any triangle is half of a parallelogram with the same base and height, hence the ½ factor.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The volume of a sphere is (4/3)·π·r³.", content: "The surface area of a sphere is 4·π·r². Both formulas assume r is the radius measured from the center to the surface.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The volume of a cube is s³, where s is the side length.", content: "The surface area of a cube is 6·s² (six square faces of area s² each).", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The volume of a cylinder is π·r²·h, where r is the radius of the base and h is the height.", content: "This combines the area of the circular base (π·r²) with the height h, so the formula is base area times height.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The quadratic formula solves ax² + bx + c = 0 as x = (-b ± √(b² - 4ac)) / (2a).", content: "The expression under the square root (b² - 4ac) is called the discriminant: positive means two real roots, zero means one repeated real root, negative means two complex roots.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The Fibonacci sequence starts with 0 and 1, and each next term is the sum of the two previous ones.", content: "The sequence begins 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, .... The ratio of successive terms approaches the golden ratio φ ≈ 1.618.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "A prime number is a whole number greater than 1 whose only positive divisors are 1 and itself.", content: "The smallest primes are 2, 3, 5, 7, 11, 13, .... Two is the only even prime. Every integer greater than 1 can be uniquely factored into primes (Fundamental Theorem of Arithmetic).", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "In a right triangle, sine, cosine, and tangent are defined as ratios of side lengths relative to one of the acute angles.", content: "For an angle θ: sin(θ) = opposite/hypotenuse, cos(θ) = adjacent/hypotenuse, tan(θ) = opposite/adjacent = sin(θ)/cos(θ).", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The interior angles of any triangle in a flat plane sum to 180°.", content: "On a curved surface (sphere or saddle) the sum differs: more than 180° on a sphere, less on a saddle, which is the basis of non-Euclidean geometry.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The interior angles of any quadrilateral sum to 360°.", content: "Any quadrilateral can be split into two triangles, each contributing 180°, for a total of 360°.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The square root of 2 is approximately 1.41421.", content: "√2 is the length of the diagonal of a unit square (by the Pythagorean theorem: 1² + 1² = 2). It was one of the first numbers proven irrational, by the ancient Greeks.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The factorial of 0 (0!) is defined as 1.", content: "By convention, the empty product equals 1. For n > 0, n! = n · (n-1) · ... · 1. For example, 5! = 120.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The slope of a line passing through two points (x₁,y₁) and (x₂,y₂) is (y₂ - y₁) / (x₂ - x₁).", content: "Slope measures the steepness and direction of a line; positive slopes rise left-to-right, negative slopes fall, and a vertical line has undefined slope.", scope: "GLOBAL" },
  { type: "RULE", category: "math", claim: "The conventional order of operations in arithmetic is Parentheses, Exponents, Multiplication/Division, Addition/Subtraction (PEMDAS).", content: "Multiplication and division have equal precedence and are evaluated left-to-right, as are addition and subtraction. Brackets of any kind always group first.", scope: "GLOBAL" },
  { type: "FACT", category: "math", claim: "The area of a trapezoid is ½ · (base₁ + base₂) · height.", content: "A trapezoid has exactly one pair of parallel sides (the two bases). The formula averages the two bases and multiplies by the perpendicular height between them.", scope: "GLOBAL" },

  // ===== HISTORY (22) =====
  { type: "FACT", category: "history", claim: "World War I lasted from 1914 to 1918.", content: "Triggered by the assassination of Archduke Franz Ferdinand of Austria-Hungary, the war involved the Allied Powers (UK, France, Russia, later USA and Italy) against the Central Powers (Germany, Austria-Hungary, Ottoman Empire). It ended with the Treaty of Versailles in 1919.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "World War II lasted from 1939 to 1945.", content: "The Allies (UK, USSR, USA, China, France and others) defeated the Axis (Germany, Italy, Japan). It was the deadliest conflict in human history, with an estimated 70–85 million deaths, and ended after Germany surrendered in May 1945 and Japan in September 1945.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The Berlin Wall fell on November 9, 1989.", content: "The wall had divided East and West Berlin since 1961. Its fall followed mass protests and the easing of East German travel restrictions, marking the symbolic end of the Cold War. Germany was reunified in October 1990.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "Apollo 11 landed humans on the Moon on July 20, 1969.", content: "NASA astronauts Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon while Michael Collins orbited above. Armstrong's first words on the lunar surface were 'That's one small step for [a] man, one giant leap for mankind.'", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The French Revolution began in 1789 with the storming of the Bastille on July 14.", content: "The revolution overthrew the French monarchy, established a republic, and led to the Reign of Terror and eventually the rise of Napoleon Bonaparte. July 14 is still celebrated in France as Bastille Day.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The United States declared independence from Great Britain on July 4, 1776.", content: "The Declaration of Independence, primarily drafted by Thomas Jefferson, announced the thirteen American colonies' separation from Britain. The Revolutionary War continued until 1783.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The Great Pyramids of Giza were built around 2,500 BCE as tombs for Egyptian pharaohs.", content: "The largest, the Great Pyramid of Khufu, was the tallest human-made structure in the world for over 3,800 years. It is the only one of the Seven Wonders of the Ancient World still largely intact.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The Roman Empire was one of the largest and most influential ancient empires, centered on the city of Rome.", content: "At its peak around 117 CE the empire stretched from Britain to Mesopotamia. The Western Empire fell in 476 CE; the Eastern (Byzantine) Empire survived until 1453.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The Industrial Revolution began in Britain in the mid-18th century.", content: "Mechanization of textile production, the steam engine, and improved iron-making transformed agrarian economies into industrial ones and led to massive urbanization. A second industrial wave followed in the 19th century with steel, chemicals, and electricity.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "Christopher Columbus reached the Americas in 1492 under Spanish sponsorship.", content: "Columbus, an Italian navigator, was seeking a westward sea route to Asia. His landfall in the Bahamas began sustained European contact with the Americas, although Norse explorers had reached North America centuries earlier.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The Magna Carta was signed by King John of England in 1215.", content: "The Magna Carta (Great Charter) limited royal power and established that even the king was subject to law. It is widely regarded as a foundational document of constitutional government and the rule of law.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "Johannes Gutenberg introduced the movable-type printing press to Europe around 1440.", content: "Gutenberg's press made mass production of books possible, dramatically lowering their cost and accelerating the spread of literacy, science, and religious ideas during the Renaissance and Reformation.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The Renaissance was a cultural and intellectual movement in Europe from roughly the 14th to the 17th century.", content: "Beginning in Italy, the Renaissance revived interest in classical Greek and Roman art, science, and philosophy, and produced figures such as Leonardo da Vinci, Michelangelo, and Galileo.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The Cold War ended around 1991 with the dissolution of the Soviet Union.", content: "The Cold War (1947–1991) was a political and ideological standoff between the Western bloc (led by the USA) and the Eastern bloc (led by the USSR) without direct large-scale conflict but marked by arms races, proxy wars, and the threat of nuclear annihilation.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "Nelson Mandela was released from prison on February 11, 1990.", content: "After 27 years of imprisonment, Mandela was freed by South African president F. W. de Klerk. Mandela was elected South Africa's first Black president in 1994 after the end of apartheid.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The RMS Titanic sank on April 15, 1912, after hitting an iceberg on its maiden voyage.", content: "More than 1,500 of the roughly 2,200 people aboard died. The disaster led to major maritime safety reforms, including the requirement that ships carry enough lifeboats for everyone on board.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The Boston Tea Party took place on December 16, 1773.", content: "American colonists dumped British tea into Boston Harbor to protest the tax on tea and the lack of colonial representation in Parliament, escalating tensions that led to the American Revolution.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "Penicillin, the first widely used antibiotic, was discovered by Alexander Fleming in 1928.", content: "Fleming noticed that a Penicillium mold had killed bacteria in a Petri dish. Mass production during World War II made penicillin widely available and revolutionized medicine.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The Wright brothers made the first sustained powered airplane flight on December 17, 1903, at Kitty Hawk, North Carolina.", content: "Orville and Wilbur Wright's aircraft, the Wright Flyer, flew for 12 seconds and covered 120 feet on its first flight. Three more flights followed the same day, the longest covering 852 feet.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The Suez Canal was opened in 1869, linking the Mediterranean Sea and the Red Sea.", content: "The 193-km canal in Egypt provides the shortest maritime route between Europe and Asia without circumnavigating Africa. It remains one of the world's most important shipping lanes.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The United Nations was founded on October 24, 1945, after the end of World War II.", content: "The UN replaced the failed League of Nations and was created to maintain international peace and security, develop friendly relations among nations, and promote social progress. October 24 is observed annually as United Nations Day.", scope: "GLOBAL" },
  { type: "FACT", category: "history", claim: "The Great Wall of China is a series of fortifications built over many centuries, primarily during the Ming dynasty (1368–1644).", content: "The wall stretches more than 20,000 km across northern China and was built to protect against raids and invasions from nomadic groups of the Eurasian Steppe.", scope: "GLOBAL" },

  // ===== TECHNOLOGY (28) =====
  { type: "FACT", category: "technology", claim: "HTML stands for HyperText Markup Language.", content: "HTML is the standard markup language used to structure content on the Web, using tags such as <h1>, <p>, and <a> to define headings, paragraphs, links, and other elements.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "CSS stands for Cascading Style Sheets.", content: "CSS is a style-sheet language used to describe the presentation (colors, layout, fonts) of a document written in HTML. 'Cascading' refers to the rules that decide which style applies when several conflict.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "JavaScript is a high-level programming language that runs in web browsers and on servers.", content: "JavaScript adds interactivity to web pages and can also be used on servers (most famously via Node.js). Despite the name, it is unrelated to the Java language.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "An API (Application Programming Interface) is a set of rules that lets software components communicate with each other.", content: "Web APIs typically expose endpoints over HTTP that return data (often JSON). For example, a weather app might call a weather service's API to retrieve the current forecast.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "REST stands for Representational State Transfer, an architectural style for designing web APIs.", content: "REST APIs use standard HTTP methods (GET to read, POST to create, PUT/PATCH to update, DELETE to remove) on resources identified by URLs, typically returning JSON. REST is stateless: each request contains everything needed to handle it.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "Relational databases store data in tables with rows and columns, while NoSQL databases use non-tabular models.", content: "Relational databases (PostgreSQL, MySQL, SQLite) enforce a fixed schema and use SQL. NoSQL databases (MongoDB, Redis, Cassandra) use flexible documents, key-value pairs, wide columns, or graphs and trade some consistency for horizontal scalability.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "Machine learning is a branch of artificial intelligence in which systems learn patterns from data instead of being explicitly programmed.", content: "Common types include supervised learning (labeled examples), unsupervised learning (find structure in unlabeled data), and reinforcement learning (learn by trial and error with rewards).", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "Deep learning is a subfield of machine learning that uses many-layered (deep) neural networks.", content: "Deep learning has driven recent breakthroughs in image recognition, speech, and language. Large language models such as GPT and GLM are deep neural networks trained on vast text corpora.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "A neural network is a model of interconnected nodes (neurons) organized in layers that transform input data into output.", content: "Each connection has a weight adjusted during training. A typical network has an input layer, one or more hidden layers, and an output layer. 'Deep' networks simply have many hidden layers.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "The internet is the global network of interconnected computer networks, while the World Wide Web is the system of documents and resources accessed over it.", content: "The internet carries many services (email, file transfer, gaming, video calls) of which the Web (HTTP pages and sites) is just one. Tim Berners-Lee invented the Web at CERN in 1989–1991.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "TCP/IP is the foundational communication protocol suite of the internet.", content: "IP (Internet Protocol) routes packets across networks to an address; TCP (Transmission Control Protocol) ensures reliable, in-order delivery of packets between applications.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "HTTPS is HTTP encrypted with TLS (Transport Layer Security), formerly called SSL.", content: "HTTPS prevents eavesdropping, tampering, and forgery between a client and server. Browsers display a padlock icon for HTTPS connections. TLS certificates are issued by certificate authorities.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "Git is a distributed version-control system that tracks changes to files and coordinates work among multiple contributors.", content: "Git was created by Linus Torvalds in 2005. Developers commit changes to local repositories and can synchronize via hosting platforms such as GitHub, GitLab, or Bitbucket.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "Cloud computing delivers computing services (servers, storage, databases, software) over the internet on demand.", content: "Common service models are IaaS (Infrastructure as a Service — virtual machines, e.g., AWS EC2), PaaS (Platform as a Service — managed runtimes, e.g., Heroku), and SaaS (Software as a Service — ready-to-use apps, e.g., Gmail).", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "Docker is a platform for packaging software into containers that run consistently across environments.", content: "A container bundles an application with its libraries and settings in a single image. Containers are lighter than virtual machines because they share the host operating system's kernel.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "A CDN (Content Delivery Network) is a distributed network of servers that caches and serves web content close to users.", content: "CDNs reduce latency and load on origin servers by caching static assets (images, CSS, JavaScript) at edge locations worldwide. Major CDNs include Cloudflare, Akamai, and Fastly.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "DNS (Domain Name System) translates human-readable domain names into IP addresses.", content: "When you type example.com, a DNS resolver returns the server's IP so the browser can connect. DNS is organized hierarchically with root, top-level (.com, .org), and authoritative name servers.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "Python is a high-level, general-purpose programming language known for readable syntax.", content: "Created by Guido van Rossum in 1991, Python is widely used for data science, machine learning, web backends (Django, Flask), automation, and scripting.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "TypeScript is a statically typed superset of JavaScript that compiles to plain JavaScript.", content: "Created by Microsoft, TypeScript adds optional static types, interfaces, and modern language features, enabling better tooling and earlier error detection for large JavaScript codebases.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "Java is a class-based, object-oriented programming language designed to run on any platform via the Java Virtual Machine.", content: "Released by Sun Microsystems in 1995 with the slogan 'write once, run anywhere', Java is widely used in enterprise backends, Android development, and large-scale systems.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "C++ is a compiled, general-purpose programming language that extends C with object-oriented and generic features.", content: "Created by Bjarne Stroustrup, C++ is used where performance matters: operating systems, game engines, browsers, embedded systems, and high-frequency trading.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "Go (Golang) is a statically typed, compiled programming language developed at Google.", content: "Go emphasizes simplicity, fast compilation, and built-in concurrency via goroutines and channels. It is popular for cloud services, command-line tools, and infrastructure (e.g., Docker, Kubernetes).", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "Rust is a systems programming language focused on memory safety and performance without a garbage collector.", content: "Rust's ownership and borrowing model prevents whole classes of bugs (null pointer dereferences, data races) at compile time, making it popular for safe systems software, web servers, and increasingly in the Linux kernel.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "SQL (Structured Query Language) is the standard language for querying and manipulating relational databases.", content: "SQL can retrieve (SELECT), insert (INSERT), update (UPDATE), and delete (DELETE) rows, as well as define schema (CREATE TABLE) and control access (GRANT).", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "JSON (JavaScript Object Notation) is a lightweight text format for storing and exchanging structured data.", content: "JSON uses human-readable key-value pairs and arrays (e.g., {\"name\": \"Alice\", \"age\": 30}). Although derived from JavaScript, JSON is language-independent and the de-facto interchange format for web APIs.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "A URL (Uniform Resource Locator) is the address used to locate a resource on the Web.", content: "A URL typically has a scheme (https), host (example.com), optional port (:443), path (/page), and query string (?q=1). It is a type of URI (Uniform Resource Identifier).", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "A web browser is software that retrieves and renders web pages and other internet resources.", content: "Major browsers include Chrome, Firefox, Safari, and Edge. Browsers parse HTML, apply CSS, execute JavaScript, and present the result to the user, while managing navigation history and security.", scope: "GLOBAL" },
  { type: "FACT", category: "technology", claim: "An operating system is system software that manages computer hardware and software resources and provides services to programs.", content: "Common operating systems include Windows, macOS, and Linux on desktops and laptops; iOS and Android on mobile devices; and Linux distributions on most servers. The OS schedules processes, manages memory and files, and handles devices.", scope: "GLOBAL" },

  // ===== LANGUAGE (20) =====
  { type: "FACT", category: "language", claim: "The modern English alphabet has 26 letters, from A to Z.", content: "The English alphabet is derived from the Latin alphabet. The five vowels are A, E, I, O, U (sometimes Y), and the remaining 21 letters are consonants.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "Mandarin Chinese is the most spoken language in the world by number of native speakers.", content: "Mandarin has more than 900 million native speakers, primarily in China, Taiwan, and Singapore. By total speakers (native + second-language), English is the most spoken.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "English is the most spoken language in the world by total speakers (native and second-language combined).", content: "English has roughly 1.5 billion total speakers and is the dominant lingua franca of business, science, aviation, and the internet. It has around 380 million native speakers.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "Hindi is one of the most spoken languages in the world, with hundreds of millions of speakers, primarily in India.", content: "Hindi is an official language of India alongside English, written in the Devanagari script, and is mutually intelligible with Urdu in spoken form (Hindustani).", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "Spanish is a Romance language with about 500 million native speakers, the second-most spoken native language after Mandarin.", content: "Spanish originated on the Iberian Peninsula and is the official language of most countries in Latin America. It is also widely spoken in the United States.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "Arabic is a Semitic language spoken by more than 300 million people, primarily in the Middle East and North Africa.", content: "Modern Standard Arabic is used in formal writing and news media, while numerous spoken dialects (Egyptian, Levantine, Gulf, Maghrebi) differ across regions. Arabic is the liturgical language of Islam.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "Bengali is an Indo-Aryan language spoken by more than 230 million people, primarily in Bangladesh and eastern India.", content: "Bengali (Bangla) is the official language of Bangladesh and one of India's scheduled languages. International Mother Language Day is observed on February 21 to commemorate the Bengali language movement.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "Russian is an East Slavic language with about 150 million native speakers, the most geographically widespread language in Eurasia.", content: "Russian is the official language of Russia, Belarus, Kazakhstan, and Kyrgyzstan and one of the six official languages of the United Nations. It uses the Cyrillic alphabet.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "Portuguese is a Romance language spoken by about 230 million people, mainly in Brazil and Portugal.", content: "Portuguese is the official language of nine countries, including Brazil (the largest Portuguese-speaking nation), Portugal, Angola, and Mozambique.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "Urdu is an Indo-Aryan language spoken by about 70 million native speakers, primarily in Pakistan and India.", content: "Urdu is the national language of Pakistan and is mutually intelligible with Hindi in spoken form. It is written in a modified Perso-Arabic script (Nastaliq) and is closely associated with South Asian poetry.", scope: "GLOBAL" },
  { type: "RULE", category: "language", claim: "A noun is a word that names a person, place, thing, or idea.", content: "Examples of nouns include 'teacher', 'city', 'apple', and 'freedom'. Proper nouns name specific entities (e.g., 'Paris', 'Alice') and are capitalized in English.", scope: "GLOBAL" },
  { type: "RULE", category: "language", claim: "A verb is a word that expresses an action, occurrence, or state of being.", content: "Examples include 'run', 'is', 'becomes', and 'think'. Verbs change form to show tense (past, present, future), aspect, and agreement with the subject.", scope: "GLOBAL" },
  { type: "RULE", category: "language", claim: "An adjective is a word that modifies (describes) a noun or pronoun.", content: "Examples include 'red', 'tall', 'happy', and 'expensive'. Adjectives give more information about qualities such as size, color, age, or opinion.", scope: "GLOBAL" },
  { type: "RULE", category: "language", claim: "An adverb is a word that modifies a verb, adjective, or another adverb, often expressing manner, time, place, or degree.", content: "Examples include 'quickly' (manner), 'yesterday' (time), 'here' (place), and 'very' (degree). Many adverbs end in -ly, though many do not (e.g., 'fast', 'well').", scope: "GLOBAL" },
  { type: "RULE", category: "language", claim: "In active voice the subject performs the action; in passive voice the subject receives the action.", content: "Active: 'The chef cooked the meal.' Passive: 'The meal was cooked by the chef.' Active voice is usually clearer and more concise; passive voice can be useful when the actor is unknown or unimportant.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "The English idiom 'break the ice' means to start a conversation in a way that relieves tension or makes strangers feel more comfortable.", content: "Example: 'We played a quick game to break the ice before the workshop began.' The phrase is thought to come from ships breaking ice to clear a path for other vessels.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "The English idiom 'hit the books' means to study hard or to begin studying seriously.", content: "Example: 'I have exams next week, so it is time to hit the books.' The image is of striking one's head against the books through intense reading.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "The English idiom 'piece of cake' describes something that is very easy to do.", content: "Example: 'The math test was a piece of cake.' The phrase dates to the 19th century, possibly from cake-walk contests in which the best performers won a cake.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "The English idiom 'once in a blue moon' means something that happens very rarely.", content: "A blue moon is the second full moon within a single calendar month, an event that occurs roughly once every two or three years.", scope: "GLOBAL" },
  { type: "FACT", category: "language", claim: "The English idiom 'bite the bullet' means to endure a painful or difficult situation with courage.", content: "Example: 'I do not want to go to the dentist, but I will just bite the bullet.' The phrase is said to originate from soldiers biting on bullets during surgery before anesthesia.", scope: "GLOBAL" },

  // ===== HEALTH & NATURE (22) =====
  { type: "FACT", category: "health", claim: "Adults are generally advised to drink about 2 liters (roughly 8 glasses) of water per day.", content: "Actual needs vary with body size, climate, and activity. The U.S. National Academies suggest about 3.7 L/day for men and 2.7 L/day for women from all beverages and foods combined.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "Adults generally need 7 to 9 hours of sleep per night for optimal health.", content: "Children and teenagers need more. Chronic sleep deprivation is linked to obesity, diabetes, cardiovascular disease, and impaired cognition and mood.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "The five main food groups are fruits, vegetables, grains, protein foods, and dairy.", content: "A balanced diet draws from all five groups. Many guidelines (USDA MyPlate, WHO) recommend that at least half the plate be fruits and vegetables, with whole grains preferred over refined.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "Vitamin A is essential for vision, immune function, and skin health.", content: "Vitamin A is found in liver, dairy, eggs, and orange or dark green vegetables (carrots, sweet potato, spinach) as beta-carotene. Deficiency causes night blindness and weakens immunity.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "Vitamin C (ascorbic acid) supports immune function and wound healing and acts as an antioxidant.", content: "Vitamin C is found in citrus fruits, peppers, strawberries, and broccoli. Severe deficiency causes scurvy. It is water-soluble, so the body does not store much.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "Vitamin D helps the body absorb calcium and is important for bone health.", content: "Vitamin D is produced by the skin in sunlight and is also found in fatty fish and fortified foods. Deficiency can cause rickets in children and osteomalacia in adults.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "Vitamin B12 is essential for nerve function and the production of red blood cells.", content: "Vitamin B12 is found almost exclusively in animal products, so vegans may need supplements. Deficiency can cause anemia and permanent nerve damage.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "Vitamin E is a fat-soluble antioxidant that protects cell membranes from damage.", content: "Vitamin E is found in vegetable oils, nuts, seeds, and leafy greens. Deficiency is rare in healthy people.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "Vitamin K is essential for blood clotting and bone metabolism.", content: "Vitamin K is found in leafy green vegetables (K1) and produced by gut bacteria (K2). Newborns receive a vitamin K injection to prevent rare but serious bleeding.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "Adults should aim for at least 150 minutes of moderate-intensity aerobic exercise per week.", content: "WHO and major health authorities also recommend muscle-strengthening activities on 2 or more days per week. Moderate intensity means raised heart rate and breathing but still able to talk (e.g., brisk walking, cycling).", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "Body Mass Index (BMI) is calculated as weight in kilograms divided by height in meters squared (kg/m²).", content: "For adults, BMI 18.5–24.9 is considered normal, 25–29.9 overweight, and 30 or more obese. BMI is a screening tool, not a direct measure of body fat, and may misclassify muscular individuals.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "Normal adult blood pressure is generally considered to be less than 120/80 mmHg.", content: "The top number (systolic) is pressure during heartbeats, the bottom (diastolic) between beats. Sustained readings of 130/80 mmHg or higher are typically classified as hypertension.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "A typical 8-ounce cup of brewed coffee contains about 95 milligrams of caffeine.", content: "Caffeine content varies widely by bean, brew method, and serving size: espresso has about 60–65 mg per shot, and a 16-ounce brewed coffee can exceed 200 mg. Most healthy adults tolerate up to about 400 mg/day.", scope: "GLOBAL" },
  { type: "FACT", category: "nature", claim: "The water cycle describes the continuous movement of water through evaporation, condensation, and precipitation.", content: "The sun evaporates water from oceans, lakes, and soil; water vapor condenses into clouds; and precipitation returns water to the surface, where it flows or infiltrates back to start the cycle again.", scope: "GLOBAL" },
  { type: "FACT", category: "nature", claim: "The carbon cycle is the movement of carbon between the atmosphere, oceans, biosphere, and geosphere.", content: "Plants absorb atmospheric CO₂ through photosynthesis; respiration, decay, and combustion return it. Burning fossil fuels has rapidly added CO₂ to the atmosphere, driving modern climate change.", scope: "GLOBAL" },
  { type: "FACT", category: "nature", claim: "A food chain shows how energy is transferred from one organism to another in an ecosystem.", content: "A typical chain is: sun → grass (producer) → rabbit (primary consumer) → fox (secondary consumer) → decomposers. Most ecosystems are better described as food webs, with many overlapping chains.", scope: "GLOBAL" },
  { type: "FACT", category: "nature", claim: "An ecosystem is a community of living organisms together with the non-living components of their environment.", content: "Ecosystems can be large (a rainforest, a coral reef) or small (a pond, a rotting log). Energy flows through ecosystems and matter cycles within them.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "The human heart pumps blood through the circulatory system, beating about 100,000 times per day.", content: "The heart has four chambers (two atria, two ventricles) and pumps oxygen-poor blood to the lungs and oxygen-rich blood to the rest of the body.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "The lungs are the organs of breathing, where oxygen enters the blood and carbon dioxide leaves it.", content: "Adults have two lungs containing about 300–500 million tiny air sacs (alveoli) with a combined surface area roughly the size of a tennis court.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "Bacteria are single-celled organisms without a nucleus; viruses are much smaller and require a host cell to reproduce.", content: "Bacteria can be beneficial (gut flora) or harmful (strep throat, tuberculosis). Viruses cause illnesses such as influenza, COVID-19, and measles. Antibiotics kill bacteria but do not work against viruses.", scope: "GLOBAL" },
  { type: "FACT", category: "health", claim: "A fever is generally defined as a body temperature above about 38°C (100.4°F).", content: "Fever is part of the body's immune response to infection. Most fevers in adults are not dangerous below about 39.4°C (103°F), but very high fevers or fevers in infants require prompt medical attention.", scope: "GLOBAL" },
  { type: "FACT", category: "nature", claim: "Photosynthesis is the process by which plants, algae, and some bacteria convert sunlight into chemical energy.", content: "Chlorophyll in plant chloroplasts captures light energy to convert CO₂ and water into glucose and oxygen. This process supplies the oxygen we breathe and the food chain's energy base.", scope: "GLOBAL" },

  // ===== SPACE (17) =====
  { type: "FACT", category: "space", claim: "The solar system has eight planets, in order from the Sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.", content: "The four inner planets are small, rocky, terrestrial worlds; the four outer planets are gas and ice giants. Pluto was reclassified as a dwarf planet in 2006.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "The Sun is a star at the center of our solar system.", content: "The Sun is a roughly 4.6-billion-year-old yellow dwarf (G-type) star. It accounts for about 99.8% of the solar system's mass and powers nearly all life on Earth through sunlight.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "Earth is on average about 150 million kilometers from the Sun, a distance defined as 1 astronomical unit (AU).", content: "Light takes about 8 minutes 20 seconds to travel this distance. Earth's orbit is slightly elliptical, so distance ranges from about 147 million km at perihelion to 152 million km at aphelion.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "The Moon is Earth's only natural satellite and the closest large body to Earth.", content: "The Moon is about 384,400 km away on average and is in synchronous rotation, so it always shows the same face to Earth. Its gravity causes ocean tides.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "A light-year is the distance light travels in one year, about 9.46 trillion kilometers.", content: "Because light has a finite speed, looking at distant stars means looking back in time. The nearest star system, Alpha Centauri, is about 4.37 light-years away.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "The Milky Way is the barred spiral galaxy that contains our solar system.", content: "The Milky Way contains an estimated 100–400 billion stars and is about 100,000 light-years across. Our solar system lies about 27,000 light-years from the galactic center.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "The Big Bang theory states that the universe began about 13.8 billion years ago from an extremely hot, dense state.", content: "Evidence includes the observed expansion of the universe (Hubble's law) and the cosmic microwave background radiation, the faint afterglow of the early universe.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "A black hole is a region of spacetime where gravity is so strong that nothing, not even light, can escape.", content: "Black holes form when massive stars collapse at the end of their lives. The boundary beyond which escape is impossible is called the event horizon.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "The International Space Station (ISS) is a habitable space station orbiting Earth at an altitude of about 400 km.", content: "The ISS has been continuously crewed since November 2000 and travels at about 28,000 km/h, circling Earth roughly every 90 minutes. It is a joint project of NASA, Roscosmos, ESA, JAXA, and CSA.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "Mars rovers are robotic vehicles sent to explore the surface of Mars.", content: "Notable rovers include Sojourner (1997), Spirit and Opportunity (2004), Curiosity (2012), Perseverance (2021), and China's Zhurong (2021). They have searched for water, signs of past life, and resources for future human missions.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "Pluto was reclassified as a dwarf planet by the International Astronomical Union in 2006.", content: "Pluto failed the third IAU planet criterion: it has not 'cleared its neighborhood' of other objects in its orbit. It is now the prototype of the plutoid class of dwarf planets.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "Jupiter is the largest planet in our solar system.", content: "Jupiter is a gas giant with a mass more than twice that of all other planets combined. Its Great Red Spot is a storm that has raged for at least 350 years, and it has at least 95 known moons.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "Saturn is famous for its prominent ring system, made mostly of ice and rock particles.", content: "Saturn is a gas giant and the second-largest planet. Its rings span up to about 280,000 km in diameter but are only about 10 m thick on average. Saturn has 146 confirmed moons, the most of any planet.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "Mercury is the closest planet to the Sun and the smallest planet in the solar system.", content: "Mercury has no atmosphere to retain heat, so temperatures swing from about -180°C at night to 430°C in daylight. A year on Mercury is just 88 Earth days.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "Venus is the hottest planet in the solar system due to a runaway greenhouse effect.", content: "Although Mercury is closer to the Sun, Venus's thick CO₂ atmosphere traps heat, giving it an average surface temperature of about 465°C — hotter than any other planet.", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "Mars is called the Red Planet because of the iron oxide (rust) on its surface.", content: "Mars is a cold desert world with a thin CO₂ atmosphere. It has the tallest volcano in the solar system (Olympus Mons, ~22 km high) and the deepest canyon (Valles Marineris).", scope: "GLOBAL" },
  { type: "FACT", category: "space", claim: "A comet is a small icy body that develops a tail of gas and dust when it nears the Sun.", content: "Comets come from the Kuiper Belt and Oort Cloud at the outer edge of the solar system. The tail always points away from the Sun because it is pushed by the solar wind.", scope: "GLOBAL" },

  // ===== EVERYDAY / PRACTICAL (16) =====
  { type: "PROCEDURE", category: "everyday", claim: "To make a water rocket, partially fill a plastic bottle with water, fit a tight launcher into its mouth, pump in air pressure, and release the bottle so the pressurized air forces the water out and propels the bottle upward.", content: "A typical water rocket uses a 1–2 liter PET bottle with about one-third filled with water. Air is pumped in through a stopper or valve until pressure builds (e.g., 40–60 psi), then a quick release lets the bottle launch. The water is reaction mass, so the rocket flies much higher than with air alone. Always launch outdoors in an open area, away from people and property, and never pressurize beyond the bottle's safe rating.", scope: "GLOBAL" },
  { type: "PROCEDURE", category: "everyday", claim: "To boil a soft-boiled egg, cook it in boiling water for about 6 minutes; for a hard-boiled egg, cook for 10–12 minutes.", content: "Start eggs at room temperature or from boiling water for predictable results. After cooking, immediately place eggs in cold water to stop further cooking and make peeling easier. Soft eggs have runny yolks; hard eggs are fully set.", scope: "GLOBAL" },
  { type: "PROCEDURE", category: "everyday", claim: "To make a basic cup of coffee, brew about 2 tablespoons (10 g) of ground coffee per 180 ml (6 oz) of hot water just off the boil.", content: "Use water at about 90–96°C (just off the boil) to avoid burning the grounds. Brew time depends on method: about 4 minutes for a French press, 2–4 minutes for pour-over, and 25–30 seconds for espresso. Adjust the coffee-to-water ratio to taste.", scope: "GLOBAL" },
  { type: "PROCEDURE", category: "everyday", claim: "To tie a basic four-in-hand knot, drape a tie around the neck with the wide end on the right and lower than the narrow end, cross the wide end over and back under the narrow end, then up through the loop, down through the front knot, and tighten.", content: "The four-in-hand produces a slightly asymmetrical, versatile knot suitable for most collars. Slide the knot up to the collar while holding the narrow end, and adjust the dimple for a polished look.", scope: "GLOBAL" },
  { type: "PROCEDURE", category: "everyday", claim: "To swim, lie flat in the water, keep the head aligned with the spine, breathe by turning the head to one side between strokes, and use alternating arm pulls with a steady flutter kick.", content: "Relaxation and body position are key: a horizontal, streamlined body floats and moves more easily. Beginners should start in shallow water with a lifeguard present and practice floating, kicking, and breathing separately before combining them.", scope: "GLOBAL" },
  { type: "PROCEDURE", category: "everyday", claim: "To ride a bicycle, sit on the saddle with one foot on a pedal, push off with the other foot to gain momentum, pedal forward while keeping the handlebars steady, and use the brakes gently to stop.", content: "Momentum provides the stability that makes balancing easier, so start by coasting down a slight slope or with a helper steadying the saddle. Look ahead rather than down, steer gently, and apply both brakes smoothly.", scope: "GLOBAL" },
  { type: "PROCEDURE", category: "everyday", claim: "For adult CPR, push hard and fast in the center of the chest at least 5 cm deep and 100–120 times per minute, and give rescue breaths if trained; if untrained, perform continuous chest compressions.", content: "Call emergency services immediately. For hands-only CPR, focus on continuous chest compressions to the beat of 'Stayin' Alive' until help arrives. CPR can keep blood flowing to the brain and other vital organs.", scope: "GLOBAL" },
  { type: "PROCEDURE", category: "everyday", claim: "To perform the Heimlich maneuver on a choking adult, stand behind them, place a fist just above the navel, grasp the fist with the other hand, and give quick inward and upward thrusts until the object is expelled.", content: "Call emergency services first. For pregnant or obese individuals, use chest thrusts instead. Do not perform the Heimlich if the person can cough or speak — encourage them to keep coughing.", scope: "GLOBAL" },
  { type: "PROCEDURE", category: "everyday", claim: "To cook basic white rice, combine 1 part rinsed rice with 2 parts water in a pot, bring to a boil, reduce to a low simmer, cover, and cook for 15–20 minutes until the water is absorbed.", content: "Do not lift the lid during cooking, as the trapped steam cooks the rice. After cooking, let it rest off the heat for 5 minutes, then fluff with a fork. One cup of dry rice yields roughly 3 cups cooked.", scope: "GLOBAL" },
  { type: "PROCEDURE", category: "everyday", claim: "To change a flat tire, park on a flat surface, apply the parking brake, loosen the lug nuts slightly, jack up the car, remove the lug nuts and tire, mount the spare, hand-tighten the lug nuts, lower the car, and finish tightening in a star pattern.", content: "Consult the vehicle's manual for the correct jack points and torque. After changing, drive cautiously — most spare tires (especially small 'donut' spares) are limited to about 80 km/h (50 mph) and short distances. Have the original tire repaired or replaced promptly.", scope: "GLOBAL" },
  { type: "FACT", category: "everyday", claim: "The emergency phone number in the United States and Canada is 911.", content: "Calling 911 connects callers to police, fire, or medical emergency services. The service also supports text-to-911 in many areas for people who cannot safely call.", scope: "GLOBAL" },
  { type: "FACT", category: "everyday", claim: "The emergency phone number in the United Kingdom is 999 (or 112).", content: "Both 999 and 112 connect callers to police, fire, ambulance, or coastguard services. 112 is the standard emergency number across the European Union and works on all mobile networks.", scope: "GLOBAL" },
  { type: "FACT", category: "everyday", claim: "The general emergency phone number across the European Union is 112.", content: "112 works free of charge from any phone, including mobiles without a SIM card, and connects to local emergency services in all EU member states and many other countries.", scope: "GLOBAL" },
  { type: "FACT", category: "everyday", claim: "The emergency phone number for police in Egypt is 122.", content: "Other Egyptian emergency numbers include 123 for ambulance, 180 for fire, and 126 for tourism police. Mobile users can also dial 112 to be routed to local services.", scope: "GLOBAL" },
  { type: "FACT", category: "everyday", claim: "Earth is divided into 24 standard time zones, each nominally one hour apart, based on longitude from the prime meridian.", content: "Time zones are offset from Coordinated Universal Time (UTC), such as UTC+2 for Cairo and UTC+5:30 for India. Some zones use 30- or 45-minute offsets, and daylight saving time shifts clocks forward in summer in many regions.", scope: "GLOBAL" },
  { type: "FACT", category: "everyday", claim: "Major world currencies include the US dollar (USD), euro (EUR), British pound (GBP), Japanese yen (JPY), Egyptian pound (EGP), Saudi riyal (SAR), and UAE dirham (AED).", content: "Currency exchange rates fluctuate based on supply and demand, interest rates, inflation, and economic stability. The US dollar is the world's primary reserve currency and is widely used in international trade.", scope: "GLOBAL" },
];

/**
 * Seed the general knowledge base into a tenant + application.
 *
 * Creates one KnowledgeSource (upserted by tenantId + title), then one
 * KnowledgeItem per entry in GENERAL_KNOWLEDGE_BASE, skipping claims that
 * already exist for that source. KnowledgeEvidence rows are created for each
 * item's evidence entries. Content vectors are built using the shared
 * buildTermVector + serializeVector helpers from ./vectors.
 */
export async function seedGeneralKnowledge(
  tenantId: string,
  applicationId: string,
): Promise<{ sourceId: string; itemCount: number }> {
  const now = new Date();

  // Upsert the single source for this tenant.
  let source = await db.knowledgeSource.findFirst({
    where: { tenantId, title: GENERAL_KNOWLEDGE_SOURCE.title },
  });
  if (!source) {
    source = await db.knowledgeSource.create({
      data: {
        tenantId,
        sourceType: GENERAL_KNOWLEDGE_SOURCE.sourceType,
        title: GENERAL_KNOWLEDGE_SOURCE.title,
        author: GENERAL_KNOWLEDGE_SOURCE.author,
        trustLevel: GENERAL_KNOWLEDGE_SOURCE.trustLevel,
        verificationStatus: GENERAL_KNOWLEDGE_SOURCE.verificationStatus,
        dataClassification: GENERAL_KNOWLEDGE_SOURCE.dataClassification,
        publishedAt: now,
      },
    });
  } else {
    source = await db.knowledgeSource.update({
      where: { id: source.id },
      data: {
        sourceType: GENERAL_KNOWLEDGE_SOURCE.sourceType,
        author: GENERAL_KNOWLEDGE_SOURCE.author,
        trustLevel: GENERAL_KNOWLEDGE_SOURCE.trustLevel,
        verificationStatus: GENERAL_KNOWLEDGE_SOURCE.verificationStatus,
        dataClassification: GENERAL_KNOWLEDGE_SOURCE.dataClassification,
      },
    });
  }

  let itemCount = 0;
  for (const item of GENERAL_KNOWLEDGE_BASE) {
    const existing = await db.knowledgeItem.findFirst({
      where: { tenantId, sourceId: source.id, claim: item.claim },
    });
    if (existing) continue;

    const vectorText = `${item.claim} ${item.content} ${item.category}`;
    const knowledgeItem = await db.knowledgeItem.create({
      data: {
        tenantId,
        applicationId,
        sourceId: source.id,
        type: item.type,
        scope: item.scope ?? "APPLICATION",
        claim: item.claim,
        content: item.content,
        contentVector: serializeVector(buildTermVector(vectorText)),
        status: "ACTIVE",
        confidence: 0.8,
        validFrom: item.validFrom ?? now,
        refreshSchedule: "manual",
        lastRefreshedAt: now,
      },
    });

    if (item.evidence && item.evidence.length > 0) {
      for (const e of item.evidence) {
        await db.knowledgeEvidence.create({
          data: {
            tenantId,
            knowledgeItemId: knowledgeItem.id,
            sourceId: source.id,
            evidenceType: e.evidenceType,
            content: e.content,
            section: e.section ?? null,
          },
        });
      }
    }
    itemCount++;
  }

  return { sourceId: source.id, itemCount };
}
