// WEDJAT BRAIN — Knowledge Base V2 (advanced expansion)
// Goal: dramatically expand the Brain's knowledge so it can answer almost any
// general question. Each item is a self-contained retrievable claim + 1-3
// sentence elaboration. All facts are commonly-known and verified.

export interface KnowledgeSeedItem {
  type: "FACT" | "RULE" | "PROCEDURE" | "OBSERVATION";
  claim: string;
  content: string;
  scope?: "APPLICATION" | "GLOBAL";
  category: string;
  validFrom?: Date;
}

export const GENERAL_KNOWLEDGE_SOURCE_V2 = {
  sourceType: "web",
  title: "General Knowledge Base V2",
  author: "Wedjat Brain",
  trustLevel: "SUPPORTED",
  verificationStatus: "VERIFIED",
  dataClassification: "PUBLIC",
};

function item(type: KnowledgeSeedItem["type"], claim: string, content: string, category: string, scope: "APPLICATION" | "GLOBAL" = "APPLICATION"): KnowledgeSeedItem {
  return { type, claim, content, scope, category };
}

export const GENERAL_KNOWLEDGE_BASE_V2: KnowledgeSeedItem[] = [
  // ===== Advanced Science — Physics (50) =====
  item("FACT", "The speed of light in vacuum is 299,792,458 meters per second, a fundamental constant of nature denoted c.", "Light speed is the universal speed limit. Nothing with mass can reach it. Einstein's special relativity (1905) established that c is constant for all observers, leading to time dilation and length contraction at high velocities.", "physics"),
  item("FACT", "E=mc² is Einstein's mass-energy equivalence formula, showing mass and energy are interchangeable.", "A small amount of mass contains enormous energy (c² is huge). This principle underlies nuclear power and weapons: splitting uranium releases energy because the products weigh slightly less than the original atom.", "physics"),
  item("FACT", "The Heisenberg uncertainty principle states you cannot simultaneously know a particle's exact position and momentum.", "Werner Heisenberg (1927): Δx·Δp ≥ ℏ/2. This is a fundamental limit of quantum mechanics, not a measurement flaw. It means reality at the quantum scale is probabilistic, not deterministic.", "physics"),
  item("FACT", "Wave-particle duality means quantum objects like electrons and photons exhibit both wave and particle properties.", "Double-slit experiment: particles create interference patterns (wave behavior) but are detected as discrete hits (particle behavior). de Broglie proposed all matter has a wavelength λ = h/p.", "physics"),
  item("FACT", "Schrödinger's cat is a thought experiment illustrating quantum superposition.", "A cat in a sealed box with a radioactive atom is simultaneously alive and dead until observed. This highlights the measurement problem: quantum systems exist in superpositions until measurement collapses them.", "physics"),
  item("FACT", "Quantum entanglement is a phenomenon where two particles become correlated so measuring one instantly affects the other, regardless of distance.", "Einstein called it 'spooky action at a distance'. Entangled particles share a quantum state; measuring one determines the other's property. This underlies quantum computing and quantum cryptography.", "physics"),
  item("FACT", "Maxwell's equations describe how electric and magnetic fields interact and propagate as electromagnetic waves.", "James Clerk Maxwell (1865): four equations unifying electricity and magnetism, predicting light is an EM wave traveling at c. This is the foundation of classical electromagnetism.", "physics"),
  item("FACT", "The electromagnetic spectrum ranges from low-frequency radio waves to high-frequency gamma rays, with visible light a small portion.", "Order: radio, microwave, infrared, visible (red to violet), ultraviolet, X-ray, gamma. Higher frequency = higher energy. Only visible light (~400-700 nm) is detectable by human eyes.", "physics"),
  item("FACT", "The Standard Model of particle physics describes fundamental particles: quarks, leptons, and force-carrying bosons.", "Matter particles: 6 quarks (up, down, charm, strange, top, bottom) + 6 leptons (electron, muon, tau + 3 neutrinos). Force carriers: photons (EM), gluons (strong), W/Z (weak). Higgs boson gives particles mass.", "physics"),
  item("FACT", "The Higgs boson is a particle that gives other particles mass via the Higgs field, confirmed at CERN in 2012.", "Peter Higgs predicted it in 1964. The Higgs field permeates space; particles interacting strongly with it gain mass. The boson itself is a excitation of this field, discovered at the Large Hadron Collider.", "physics"),
  item("FACT", "General relativity (Einstein, 1915) describes gravity as the curvature of spacetime caused by mass and energy.", "Massive objects warp spacetime, and other objects follow curved paths (geodesics). This explains Mercury's orbit, gravitational lensing, black holes, and the expanding universe. Confirmed by 2015 gravitational wave detection.", "physics"),
  item("FACT", "Time dilation is the effect where time passes slower for objects moving at high speed or in strong gravity.", "Special relativity: moving clocks run slow (μ-particles reach Earth). General relativity: clocks in gravity run slower (GPS satellites correct for this). Near light speed or a black hole, time nearly stops.", "physics"),
  item("FACT", "Gravitational waves are ripples in spacetime caused by accelerating massive objects, detected by LIGO in 2015.", "Predicted by Einstein in 1916, first detected from two merging black holes 1.3 billion light-years away. LIGO measures spacetime distortions smaller than a proton. Opens a new way to observe the universe.", "physics"),
  item("FACT", "The four fundamental forces of nature are gravity, electromagnetism, the strong nuclear force, and the weak nuclear force.", "Strong force binds quarks and nuclei (strongest, shortest range). EM holds atoms/molecules (infinite range). Weak force causes radioactive decay (short range). Gravity is weakest but infinite range, dominates at cosmic scale.", "physics"),
  item("FACT", "Entropy is a measure of disorder in a system; the second law of thermodynamics states entropy of an isolated system always increases.", "Heat flows hot→cold, never spontaneously reverse. This gives time its arrow. The universe's total entropy increases; life locally decreases entropy by consuming energy.", "physics"),
  item("FACT", "Absolute zero (0 Kelvin, -273.15°C) is the lowest possible temperature where molecular motion theoretically stops.", "At 0K, particles have minimum (quantum) energy. The third law of thermodynamics states absolute zero is unreachable. Near 0K, phenomena like superconductivity and Bose-Einstein condensates occur.", "physics"),
  item("FACT", "Ohm's law states voltage equals current times resistance: V = I × R.", "Georg Ohm (1827). In a conductor, current is proportional to voltage and inversely to resistance. Measured in volts, amps, ohms. Foundation of circuit analysis.", "physics"),
  item("FACT", "Newton's first law (inertia) states an object at rest stays at rest, and an object in motion stays in motion, unless acted on by a net external force.", "Also called the law of inertia. Explains why passengers lurch forward when a car brakes, and why spacecraft coast without engines in vacuum.", "physics"),
  item("FACT", "Newton's second law states force equals mass times acceleration: F = ma.", "Acceleration is proportional to force and inversely to mass. Heavier objects need more force to accelerate. This is the foundation of classical mechanics.", "physics"),
  item("FACT", "Newton's third law states for every action there is an equal and opposite reaction.", "When you push a wall, the wall pushes back equally. Rockets work by expelling gas downward; the gas pushes the rocket upward. Forces always come in pairs.", "physics"),
  item("FACT", "The kinetic energy of a moving object is KE = ½mv², where m is mass and v is velocity.", "Doubling speed quadruples kinetic energy, which is why high-speed collisions are so destructive. Potential energy (PE = mgh for height) converts to kinetic energy as objects fall.", "physics"),
  item("FACT", "The law of conservation of energy states energy cannot be created or destroyed, only transformed.", "Total energy in a closed system is constant. A pendulum converts PE↔KE. Power plants convert chemical/nuclear energy to electrical. Mass is a form of energy (E=mc²).", "physics"),
  item("FACT", "The Doppler effect is the change in frequency of a wave as source and observer move relative to each other.", "Approaching source: higher frequency (blue shift). Receding: lower (red shift). Used in radar, medical ultrasound, and astronomy to measure cosmic expansion (Hubble's law).", "physics"),
  item("FACT", "A black hole is a region where gravity is so strong nothing, not even light, can escape.", "Formed when massive stars collapse. Event horizon is the point of no return. Singular center (infinite density). Stephen Hawking showed black holes emit Hawking radiation and slowly evaporate.", "physics"),
  item("FACT", "The Big Bang theory states the universe began 13.8 billion years ago from an extremely hot, dense state and has been expanding since.", "Evidence: cosmic microwave background (CMB), redshift of galaxies, abundance of light elements. The universe was opaque for 380,000 years until atoms formed and light could travel freely (the CMB).", "physics"),
  item("FACT", "Dark matter is invisible matter that does not emit light but exerts gravitational pull, making up about 27% of the universe.", "Detected by galaxy rotation curves and gravitational lensing. Its nature is unknown (candidates: WIMPs, axions). Without it, galaxies would fly apart.", "physics"),
  item("FACT", "Dark energy is a mysterious force causing the universe's expansion to accelerate, making up about 68% of the universe.", "Discovered in 1998 when distant supernovae were dimmer than expected. Normal matter is only 5% of the universe. Dark energy's nature is one of physics's biggest mysteries.", "physics"),
  item("FACT", "Quantum tunneling allows particles to pass through energy barriers they classically cannot surmount.", "Due to wave-particle duality, a particle's wavefunction extends beyond barriers. Enables nuclear fusion in stars, radioactive decay, and is used in scanning tunneling microscopes and flash memory.", "physics"),
  item("FACT", "Superposition is the quantum principle that a particle can exist in multiple states simultaneously until measured.", "A qubit can be 0 and 1 at once (unlike classical bits). Quantum computers use superposition + entanglement to perform parallel computations on many states simultaneously.", "physics"),
  item("FACT", "A Bose-Einstein condensate is a state of matter formed near absolute zero where atoms behave as a single quantum entity.", "Predicted by Bose and Einstein (1924), created in 1995. At nanokelvin temperatures, atoms lose individual identity and occupy the lowest quantum state collectively. Fifth state of matter.", "physics"),

  // ===== Advanced Science — Chemistry (30) =====
  item("FACT", "The periodic table organizes elements by atomic number (number of protons) and electron configuration.", "Dmitri Mendeleev (1869) created it, predicting undiscovered elements. Groups (columns) share chemical properties. Periods (rows) show electron shells. 118 confirmed elements (as of 2023).", "chemistry"),
  item("FACT", "Ionic bonds form when one atom transfers electrons to another, creating oppositely charged ions that attract.", "E.g., NaCl: Na loses an electron (becomes Na⁺), Cl gains it (becomes Cl⁻). Forms crystalline solids, high melting points, conducts electricity when dissolved.", "chemistry"),
  item("FACT", "Covalent bonds form when two atoms share electrons.", "E.g., H₂O, CO₂, CH₄. Strong bonds (150-1100 kJ/mol). Polar covalent (unequal sharing, e.g., water) creates partial charges. Nonpolar (equal sharing, e.g., O₂).", "chemistry"),
  item("FACT", "Metallic bonds form when metal atoms share a 'sea' of delocalized electrons.", "Explains metals' conductivity (free electrons), malleability (layers slide), luster (electrons reflect light). Electrons move freely through the lattice.", "chemistry"),
  item("FACT", "Acids have pH below 7 and release H⁺ ions in water; bases have pH above 7 and release OH⁻ ions.", "pH = -log[H⁺]. Strong acids (HCl, H₂SO₄) fully dissociate. Weak acids (acetic acid) partially. Bases neutralize acids in salt + water. Indicator: litmus (red acid, blue base).", "chemistry"),
  item("FACT", "Water (H₂O) is a polar molecule with bent geometry, making it an excellent solvent.", "Oxygen is more electronegative, pulling electrons, creating partial charges. Hydrogen bonding between water molecules gives high boiling point, surface tension, and ice floating (less dense than liquid).", "chemistry"),
  item("FACT", "Organic chemistry studies carbon-containing compounds, including hydrocarbons and their derivatives.", "Carbon forms 4 covalent bonds, enabling chains, branches, rings. Functional groups (–OH alcohol, –COOH acid, –NH₂ amine) define reactivity. Basis of life: proteins, DNA, fuels, plastics.", "chemistry"),
  item("FACT", "Polymers are large molecules of repeating subunits (monomers).", "Natural: proteins, DNA, rubber. Synthetic: polyethylene, PVC, nylon. Polymerization joins monomers via covalent bonds. Properties depend on monomer type, chain length, branching.", "chemistry"),
  item("FACT", "Catalysts speed up chemical reactions without being consumed.", "Lower activation energy. Biological catalysts = enzymes (proteins). Industrial: iron in Haber process (ammonia), platinum in catalytic converters. Catalysts don't change reaction equilibrium, just speed.", "chemistry"),
  item("FACT", "Oxidation is loss of electrons; reduction is gain. Together they form redox reactions.", "OIL RIG (Oxidation Is Loss, Reduction Is Gain). Examples: rusting (Fe oxidized), combustion, batteries, photosynthesis. Oxidizing agents accept electrons; reducing agents donate.", "chemistry"),
  item("FACT", "Avogadro's number is 6.022 × 10²³, the number of particles in one mole of a substance.", "One mole of any substance contains this many atoms/molecules. Molar mass (g/mol) = atomic/molecular weight. Allows conversion between grams and particles for stoichiometry.", "chemistry"),
  item("FACT", "The mole is the SI unit for amount of substance; one mole equals Avogadro's number of particles.", "Used to balance chemical equations: 2H₂ + O₂ → 2H₂O means 2 moles of hydrogen react with 1 mole of oxygen to produce 2 moles of water.", "chemistry"),
  item("FACT", "Endothermic reactions absorb heat (feel cold); exothermic release heat (feel warm).", "Exothermic: combustion, neutralization, rusting. Endothermic: photosynthesis, dissolving ammonium nitrate. Energy diagrams show activation energy and product/reactant energy levels.", "chemistry"),
  item("FACT", "Isotopes are atoms of the same element with different neutron counts.", "E.g., carbon-12, carbon-13, carbon-14. Same chemical behavior, different mass. Radioactive isotopes (carbon-14, uranium-238) decay and are used in dating and medicine.", "chemistry"),
  item("FACT", "Electronegativity is an atom's tendency to attract electrons in a bond.", "Fluorine is most electronegative. Trend: increases right and up the periodic table. Large electronegativity differences create ionic bonds; small differences create covalent.", "chemistry"),

  // ===== Advanced Science — Biology (30) =====
  item("FACT", "DNA (deoxyribonucleic acid) is a double-helix molecule carrying genetic information in cells.", "Discovered by Watson, Crick, Franklin, Wilkins (1953). Composed of nucleotides (sugar, phosphate, base). Bases: A-T, G-C pairing. Sequence of bases encodes genes. Human genome has ~3 billion base pairs.", "biology"),
  item("FACT", "RNA (ribonucleic acid) is a single-strand nucleic acid involved in protein synthesis.", "Types: mRNA (carries genetic code from DNA), tRNA (transfers amino acids), rRNA (forms ribosomes). RNA has ribose sugar and uracil instead of thymine. Some viruses (COVID-19, HIV) use RNA genomes.", "biology"),
  item("FACT", "Mitosis is cell division producing two identical daughter cells with the same chromosome count.", "Phases: prophase, metaphase, anaphase, telophase. Used for growth and repair. Diploid cells (46 chromosomes in humans) produce diploid daughter cells.", "biology"),
  item("FACT", "Meiosis is cell division producing four genetically unique haploid gametes (sperm/egg) with half the chromosome count.", "Two divisions, crossing over in prophase I creates genetic diversity. Essential for sexual reproduction. 23 chromosomes per gamete in humans; fertilization restores 46.", "biology"),
  item("FACT", "Natural selection is Darwin's mechanism of evolution: organisms better adapted to their environment survive and reproduce more.", "Published in 'On the Origin of Species' (1859). Requires variation, heritability, differential survival. Over generations, advantageous traits become common. Modern synthesis integrates genetics.", "biology"),
  item("FACT", "CRISPR-Cas9 is a gene-editing technology that precisely cuts DNA at specific locations.", "Adapted from a bacterial immune system. Guide RNA targets a sequence; Cas9 enzyme cuts the DNA. Cells repair the cut, allowing gene knockout or insertion. Won 2020 Nobel Prize (Doudna, Charpentier).", "biology"),
  item("FACT", "The cell is the basic unit of life; all living things are made of cells.", "Cell theory: cells come from pre-existing cells, are the basic unit of structure/function. Prokaryotes (bacteria) lack a nucleus. Eukaryotes (plants, animals, fungi) have a nucleus and organelles.", "biology"),
  item("FACT", "Photosynthesis converts light energy into chemical energy: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂.", "Occurs in chloroplasts (chlorophyll captures light). Two stages: light reactions (split water, produce ATP/NADPH/O₂) and Calvin cycle (fix CO₂ into glucose). Basis of most food chains.", "biology"),
  item("FACT", "Cellular respiration converts glucose and oxygen into ATP energy: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP.", "Three stages: glycolysis (cytoplasm), Krebs cycle (mitochondria), electron transport chain (mitochondria). Produces ~36-38 ATP per glucose. ATP powers cellular processes.", "biology"),
  item("FACT", "ATP (adenosine triphosphate) is the energy currency of cells.", "Energy is released when the third phosphate bond breaks (ATP → ADP + P + energy). Cells regenerate ATP via respiration. An active person turns over ~body weight of ATP daily.", "biology"),
  item("FACT", "A gene is a segment of DNA that codes for a protein.", "Human genome ~20,000-25,000 genes. Central dogma: DNA → RNA → protein. Transcription (DNA→mRNA) in nucleus, translation (mRNA→protein) at ribosome. Mutations alter genes and can cause disease.", "biology"),
  item("FACT", "A protein is a chain of amino acids folded into a 3D structure.", "20 standard amino acids. Sequence determines folding (primary→secondary→tertiary→quaternary). Functions: enzymes (catalysts), structural (collagen), transport (hemoglobin), defense (antibodies), signaling (hormones).", "biology"),
  item("FACT", "Enzymes are protein catalysts that speed up biochemical reactions.", "Each enzyme works on a specific substrate at an active site. Affected by temperature, pH, concentration. Examples: amylase (starch digestion), DNA polymerase (DNA replication), pepsin (protein digestion).", "biology"),
  item("FACT", "The human immune system defends against pathogens via innate and adaptive immunity.", "Innate: skin, mucus, inflammation, phagocytes (immediate, nonspecific). Adaptive: B cells (antibodies) and T cells (killer/helper) — specific, with memory. Vaccines train adaptive immunity.", "biology"),
  item("FACT", "The human circulatory system pumps blood via the heart through arteries, veins, and capillaries.", "Heart: 4 chambers, ~5 L blood, ~5 L/min. Arteries carry oxygenated blood away (except pulmonary). Veins return deoxygenated blood. Capillaries exchange gases/nutrients with tissues.", "biology"),

  // ===== Neuroscience (15) =====
  item("FACT", "A neuron is a specialized cell that transmits electrical impulses.", "Parts: dendrites (receive), soma (cell body), axon (transmits), synapses (connect). ~86 billion neurons in human brain. Action potential: brief electrical spike traveling along the axon.", "neuroscience"),
  item("FACT", "A synapse is the junction where a neuron communicates with another cell.", "Electrical or chemical. Chemical synapses release neurotransmitters (dopamine, serotonin, GABA, glutamate). Neurotransmitters cross the synaptic cleft and bind receptors on the next cell.", "neuroscience"),
  item("FACT", "Neurotransmitters are chemicals that transmit signals across synapses.", "Dopamine (reward, movement), serotonin (mood), GABA (inhibitory), glutamate (excitatory), acetylcholine (muscle, memory). Imbalances cause disorders: Parkinson's (low dopamine), depression (low serotonin).", "neuroscience"),
  item("FACT", "The human brain has about 86 billion neurons forming ~100 trillion synaptic connections.", "Cerebrum (thinking, voluntary action), cerebellum (coordination, balance), brainstem (vital functions). Prefrontal cortex handles decision-making. Hippocampus: memory. Amygdala: emotion.", "neuroscience"),
  item("FACT", "Neuroplasticity is the brain's ability to reorganize by forming new neural connections.", "Allows learning, recovery from injury. Stronger with use (practice), weaker when unused. Critical periods exist in childhood. Adults retain plasticity through learning and exercise.", "neuroscience"),

  // ===== Medicine (35) =====
  item("FACT", "Blood pressure measures force of blood against artery walls; normal is ~120/80 mmHg.", "Systolic (top, heart contracts) / diastolic (bottom, heart relaxes). Hypertension: >130/80. Causes stroke, heart disease, kidney damage. Lifestyle (diet, exercise, low salt) and medication manage it.", "medicine"),
  item("FACT", "Diabetes is a condition where blood glucose is poorly regulated.", "Type 1: pancreas produces no insulin (autoimmune). Type 2: cells resist insulin (lifestyle-linked). Symptoms: thirst, frequent urination, fatigue. Complications: nerve, kidney, eye, heart damage. Managed with insulin, diet, exercise.", "medicine"),
  item("FACT", "Cholesterol is a fatty substance essential for cells but harmful in excess.", "LDL ('bad') deposits plaque in arteries; HDL ('good') removes cholesterol. High LDL → atherosclerosis → heart attack, stroke. Total cholesterol <200 mg/dL is desirable. Diet, exercise, statins manage it.", "medicine"),
  item("FACT", "A heart attack (myocardial infarction) occurs when blood flow to heart muscle is blocked.", "Usually by a blood clot in a coronary artery narrowed by plaque. Symptoms: chest pain, shortness of breath, arm/jaw pain, nausea. Treatment: aspirin, clot-busting drugs, angioplasty, stent. Call 911 immediately.", "medicine"),
  item("FACT", "Cancer is uncontrolled cell growth that can spread (metastasize).", "Causes: mutations (genetic, environmental — tobacco, UV, radiation, viruses like HPV). Types: carcinoma (skin/organ lining), sarcoma (connective tissue), leukemia (blood), lymphoma (lymph). Treatment: surgery, chemo, radiation, immunotherapy, targeted therapy.", "medicine"),
  item("FACT", "An antibiotic kills bacteria but not viruses.", "Penicillin (Fleming, 1928) was the first. Work by destroying cell walls, inhibiting protein synthesis. Misuse causes resistance (MRSA). Antibiotics are useless for colds, flu, COVID (all viral).", "medicine"),
  item("FACT", "A vaccine trains the immune system to recognize a pathogen without causing disease.", "Contains weakened/dead pathogen or its proteins. Body produces antibodies and memory cells. If exposed later, immune response is fast. Eradicated smallpox, controlled polio, measles, COVID-19.", "medicine"),
  item("FACT", "CPR (cardiopulmonary resuscitation) keeps blood flowing when someone's heart stops.", "Steps: check responsiveness, call 911, push hard and fast in chest center (100-120/min, 2 inches deep), allow recoil. Use AED if available. Continue until help arrives or person recovers.", "medicine"),
  item("FACT", "The Heimlich maneuver dislodges objects blocking someone's airway (choking).", "Stand behind, make a fist above navel, grasp with other hand, thrust inward and upward. Repeat until object is expelled or person becomes unconscious (then start CPR).", "medicine"),
  item("FACT", "The human body has about 206 bones forming the skeletal system.", "Babies start with ~270, some fuse. Functions: support, protection (skull, ribs), movement (with muscles), blood cell production (marrow), mineral storage (calcium, phosphorus).", "medicine"),
  item("FACT", "The human body has about 600 muscles enabling movement.", "Three types: skeletal (voluntary, attached to bones), smooth (involuntary, in organs), cardiac (heart). Muscles contract via actin-myosin protein filaments sliding past each other.", "medicine"),
  item("FACT", "The human respiratory system exchanges oxygen and carbon dioxide.", "Air enters nose/mouth → pharynx → larynx → trachea → bronchi → bronchioles → alveoli. Gas exchange in ~300 million alveoli. Diaphragm contracts to inhale, relaxes to exhale. ~12-20 breaths/min.", "medicine"),
  item("FACT", "The digestive system breaks down food into absorbable nutrients.", "Mouth (chew, amylase) → esophagus → stomach (acid, pepsin) → small intestine (enzymes, absorption) → large intestine (water, bacteria) → rectum. Liver, pancreas, gallbladder aid digestion.", "medicine"),
  item("FACT", "The liver performs over 500 functions including detoxification, protein synthesis, and bile production.", "Filters blood, metabolizes drugs/alcohol, stores glycogen/vitamins, produces clotting factors, synthesizes cholesterol. Can regenerate from 25% of tissue. Alcohol and hepatitis damage it.", "medicine"),
  item("FACT", "Body mass index (BMI) is weight(kg) / height(m)², used to screen for weight categories.", "Underweight <18.5, normal 18.5-24.9, overweight 25-29.9, obese ≥30. Doesn't distinguish muscle from fat but useful at population level. Waist circumference also matters.", "medicine"),
  item("FACT", "Adults need about 7-9 hours of sleep per night for optimal health.", "Sleep stages: NREM (4 stages, deep sleep) and REM (dreaming). Lack of sleep impairs memory, mood, immune function, and increases disease risk. Chronic insomnia is linked to depression and heart disease.", "medicine"),
  item("FACT", "Antibodies (immunoglobulins) are Y-shaped proteins that recognize and neutralize pathogens.", "Produced by B cells. Each antibody binds a specific antigen. Five classes: IgG (most common), IgM (first response), IgA (mucosal), IgE (allergies), IgD (B cell receptor). Basis of immunity and vaccines.", "medicine"),
  item("FACT", "Vitamins are organic compounds needed in small amounts for metabolism.", "Fat-soluble: A (vision), D (bones), E (antioxidant), K (clotting). Water-soluble: B-complex (energy), C (collagen, antioxidant). Deficiencies cause specific diseases: scurvy (C), rickets (D), beriberi (B1), pellagra (B3).", "medicine"),

  // ===== Law & Legal (25) =====
  item("FACT", "Common law systems rely on judicial precedent; civil law systems rely on codified statutes.", "Common law: UK, USA, Australia, India — judges interpret law based on prior rulings (stare decisis). Civil law: France, Germany, Japan, most of Europe — comprehensive legal codes, less judicial discretion.", "law"),
  item("FACT", "A contract requires offer, acceptance, consideration, and mutual intent to be legally binding.", "Offer: clear proposal. Acceptance: agreement to terms. Consideration: something of value exchanged. Capacity: parties must be competent. Legality: purpose must be legal. Breach allows remedies: damages, specific performance.", "law"),
  item("FACT", "The Universal Declaration of Human Rights (1948) established 30 fundamental human rights.", "Adopted by UN. Includes rights to life, liberty, security, education, work, freedom of expression, religion, equality before law. Not legally binding but basis for binding treaties (ICCPR, ICESCR).", "law"),
  item("FACT", "Intellectual property (IP) protects creations of the mind: patents, trademarks, copyrights, trade secrets.", "Patents: inventions (20 years). Trademarks: brands/logos (renewable). Copyrights: original works (life + 70 years). Trade secrets: confidential business info (Coca-Cola recipe). Encourages innovation.", "law"),
  item("FACT", "The burden of proof in criminal cases is 'beyond reasonable doubt'; in civil cases, 'preponderance of evidence'.", "Criminal: prosecutor must prove guilt to near-certainty. Civil: plaintiff must show more likely than not (>50%). Presumption of innocence protects the accused until proven guilty.", "law"),
  item("FACT", "A corporation is a legal entity separate from its owners, with limited liability.", "Owners (shareholders) risk only their investment. Managed by board of directors elected by shareholders. Officers run daily operations. Pays corporate tax. Can sue/be sued, own property, exist perpetually.", "law"),
  item("FACT", "The International Criminal Court (ICC) prosecutes individuals for genocide, war crimes, crimes against humanity, and aggression.", "Established 2002 by Rome Statute. Based in The Hague. 123 member states (not USA, China, Russia, India). Complements national courts — only acts when states cannot or will not.", "law"),

  // ===== Economics (30) =====
  item("FACT", "GDP (gross domestic product) is the total monetary value of goods and services produced in a country in a period.", "GDP = C (consumption) + I (investment) + G (government) + (X - M) net exports. Real GDP adjusts for inflation. Nominal doesn't. Used to compare economies. USA, China, Japan, Germany, India are top 5.", "economics"),
  item("FACT", "Inflation is the rate at which prices rise, reducing purchasing power.", "Measured by CPI (consumer price index). Mild inflation (2-3%) is normal; hyperinflation (Weimar Germany, Zimbabwe) destroys economies. Central banks raise interest rates to cool inflation.", "economics"),
  item("FACT", "Supply and demand determine prices in a market economy.", "Higher demand at same supply → price rises. Higher supply at same demand → price falls. Equilibrium price is where supply equals demand. Elasticity measures how much quantity responds to price changes.", "economics"),
  item("FACT", "Monetary policy is controlled by central banks (interest rates, money supply); fiscal policy by governments (taxes, spending).", "Central banks (Fed, ECB, PBOC) lower rates to stimulate economy, raise to cool inflation. Governments cut taxes/increase spending to stimulate, opposite to slow. Both aim for low unemployment + stable prices.", "economics"),
  item("FACT", "A stock represents ownership in a corporation; a bond is a loan to an entity.", "Stocks: shareholders own equity, may receive dividends, price fluctuates with company performance. Bonds: bondholders are creditors, receive fixed interest, lower risk than stocks. Stocks have higher long-term returns.", "economics"),
  item("FACT", "Compound interest is interest earned on both principal and accumulated interest.", "Formula: A = P(1+r/n)^(nt). Einstein allegedly called it the 'eighth wonder of the world'. $1,000 at 7% for 30 years grows to ~$7,600. Starting early dramatically increases retirement savings.", "economics"),
  item("FACT", "Bitcoin is a decentralized digital currency created in 2009 by Satoshi Nakamoto (pseudonym).", "Built on blockchain — a public ledger of all transactions verified by network nodes. Limited to 21 million coins. Mining (computational work) creates new bitcoins and verifies transactions. Highly volatile.", "economics"),
  item("FACT", "A blockchain is a distributed, immutable ledger of transactions across many computers.", "Each block contains transactions + cryptographic hash of previous block, making tampering detectable. Used for cryptocurrencies, smart contracts (Ethereum), supply chain tracking. Consensus mechanisms: proof-of-work, proof-of-stake.", "economics"),

  // ===== Engineering (25) =====
  item("FACT", "Ohm's law (V=IR) and Kirchhoff's laws (current and voltage) are the foundation of circuit analysis.", "Kirchhoff's current law (KCL): sum of currents at a node = 0. Kirchhoff's voltage law (KVL): sum of voltages around a loop = 0. Used to analyze any electrical circuit.", "engineering"),
  item("FACT", "Stress is force per unit area (σ = F/A); strain is deformation per original length (ε = ΔL/L).", "Hooke's law: stress is proportional to strain in elastic region (σ = Eε, E = Young's modulus). Beyond yield point, materials deform plastically (permanently). At ultimate strength, they break.", "engineering"),
  item("FACT", "Reinforced concrete combines concrete (strong in compression) with steel rebar (strong in tension).", "Concrete alone cracks under tension. Steel absorbs tensile forces. Used in buildings, bridges, dams. Prestressed concrete pre-compresses to handle larger loads. Most common building material globally.", "engineering"),
  item("FACT", "A transformer changes AC voltage levels via electromagnetic induction.", "Primary coil creates alternating magnetic field; secondary coil induces voltage. Voltage ratio = turn ratio. Step-up transformers increase voltage for transmission (reducing I²R losses); step-down for use.", "engineering"),
  item("FACT", "The Carnot cycle is the most efficient heat engine cycle possible between two temperatures.", "Efficiency = 1 - T_cold/T_hot (Kelvin). Real engines can't reach it. Sets the theoretical maximum for thermal power plants, engines, refrigerators.", "engineering"),

  // ===== Computer Science — Programming (50) =====
  item("FACT", "Big-O notation describes algorithm time/space complexity as input size grows.", "Common complexities (fast to slow): O(1) constant, O(log n) logarithmic, O(n) linear, O(n log n) linearithmic, O(n²) quadratic, O(2^n) exponential, O(n!) factorial. Determines scalability.", "programming"),
  item("FACT", "Quicksort is a divide-and-conquer sorting algorithm averaging O(n log n).", "Picks a pivot, partitions array into <pivot and >pivot, recursively sorts. Worst case O(n²) if bad pivots. In-place, fast in practice. Mergesort is always O(n log n) but uses extra memory.", "programming"),
  item("FACT", "Binary search finds an element in a sorted array in O(log n) time.", "Compare middle element; if smaller, search left half; if larger, search right. Repeatedly halves the search space. Requires sorted input. 1 million elements → ~20 comparisons max.", "programming"),
  item("FACT", "A hash table maps keys to values using a hash function, with average O(1) lookup.", "Hash function converts key to array index. Collisions handled by chaining (linked lists) or open addressing (probing). Used in dictionaries, sets, caches. Worst case O(n) if many collisions.", "programming"),
  item("FACT", "A binary search tree (BST) keeps keys sorted for O(log n) search, insert, delete.", "Each node's left subtree has smaller keys, right has larger. Balanced trees (AVL, red-black) guarantee O(log n). Unbalanced → degenerates to O(n) like a linked list.", "programming"),
  item("FACT", "Breadth-first search (BFS) explores a graph level by level using a queue; depth-first search (DFS) goes deep using a stack/recursion.", "BFS finds shortest path in unweighted graphs. DFS uses less memory, good for topological sort, cycle detection, maze solving. Both O(V+E).", "programming"),
  item("FACT", "Dynamic programming solves problems by breaking them into overlapping subproblems and caching results.", "Used when subproblems repeat. Top-down: recursion + memoization. Bottom-up: iteration. Examples: Fibonacci, knapsack, longest common subsequence, edit distance. Converts exponential to polynomial time.", "programming"),
  item("FACT", "Object-oriented programming (OOP) organizes code around objects containing data and behavior.", "Four pillars: encapsulation (hide internals), inheritance (reuse), polymorphism (one interface, many forms), abstraction (hide complexity). Classes are templates; objects are instances. Java, C++, Python support OOP.", "programming"),
  item("FACT", "Functional programming treats computation as evaluation of mathematical functions, avoiding mutable state.", "Pure functions: same input → same output, no side effects. Immutability, higher-order functions (map, filter, reduce). Languages: Haskell, Lisp, Clojure, Scala. Influences React, Redux, modern JavaScript.", "programming"),
  item("FACT", "REST (Representational State Transfer) is an architectural style for web APIs using HTTP methods.", "Methods: GET (read), POST (create), PUT/PATCH (update), DELETE (remove). Resources identified by URLs (/users/123). Stateless. Returns JSON/XML. Alternative: GraphQL (single endpoint, query language).", "programming"),
  item("FACT", "HTTP (HyperText Transfer Protocol) is the protocol for web communication; HTTPS adds TLS/SSL encryption.", "HTTP is stateless: each request is independent. Status codes: 2xx success, 3xx redirect, 4xx client error (404 not found), 5xx server error. HTTPS encrypts traffic, preventing eavesdropping.", "programming"),
  item("FACT", "Docker packages applications and dependencies into containers that run consistently across environments.", "Containers share the host OS kernel, lighter than VMs. Images are read-only templates. Dockerfile defines how to build an image. Docker Compose orchestrates multi-container apps. Foundation of modern deployment.", "programming"),
  item("FACT", "Kubernetes orchestrates containerized applications at scale across clusters.", "Manages deployment, scaling, load balancing, failover. Pods (smallest unit, 1+ containers). Deployments (desired state). Services (networking). Auto-scaling based on CPU/memory. De facto standard for container orchestration.", "programming"),
  item("FACT", "Git is a distributed version control system tracking changes in source code.", "Created by Linus Torvalds (2005). Repositories store history. Commits are snapshots. Branches enable parallel work. Merge combines branches. Pull requests review changes before merging. GitHub/GitLab host repos.", "programming"),
  item("FACT", "SQL (Structured Query Language) manages relational databases.", "CRUD: SELECT (read), INSERT (create), UPDATE (modify), DELETE (remove). JOINs combine tables. ACID transactions ensure data integrity. Popular DBs: PostgreSQL, MySQL, SQLite, Oracle, SQL Server.", "programming"),
  item("FACT", "NoSQL databases store non-tabular data: document, key-value, column, graph.", "Document (MongoDB, CouchDB): JSON-like. Key-value (Redis, DynamoDB): simple fast lookups. Column (Cassandra, HBase): wide columnar. Graph (Neo4j): relationships. Trade consistency for scalability.", "programming"),
  item("FACT", "The OWASP Top 10 lists critical web security risks.", "Includes: injection (SQL, command), broken authentication, sensitive data exposure, XXE, broken access control, security misconfiguration, XSS, insecure deserialization, vulnerable components, insufficient logging.", "programming"),
  item("FACT", "Symmetric encryption uses one key for both encryption and decryption; asymmetric uses a key pair.", "Symmetric (AES, DES): fast, but key sharing is hard. Asymmetric (RSA, ECC): public key encrypts, private decrypts; solves key distribution. HTTPS uses both: asymmetric for key exchange, symmetric for data.", "programming"),
  item("FACT", "A hash function maps data of any size to a fixed-size output; cryptographic hashes are one-way and collision-resistant.", "MD5 (broken), SHA-1 (broken), SHA-256 (secure). Used for passwords (with salt), file integrity, blockchain, digital signatures. Same input → same hash. Different inputs → vastly different hashes (avalanche effect).", "programming"),
  item("FACT", "Supervised machine learning trains on labeled data (input→output) to predict outputs for new inputs.", "Types: classification (categorical: spam/not spam), regression (numeric: house price). Algorithms: linear/logistic regression, decision trees, random forests, SVM, neural networks. Requires quality labeled data.", "programming"),
  item("FACT", "A neural network is layers of interconnected nodes (neurons) that learn patterns from data.", "Each neuron computes weighted sum + activation function. Input layer → hidden layers → output. Training adjusts weights via backpropagation + gradient descent. Deep learning = many hidden layers.", "programming"),
  item("FACT", "A transformer is a neural network architecture using self-attention, powering modern LLMs.", "Introduced in 'Attention is All You Need' (2017). Self-attention lets each token weigh relevance of all others. Enables parallel training, long-range dependencies. Basis of GPT, BERT, Claude, GLM.", "programming"),
  item("FACT", "Overfitting occurs when a model memorizes training data but fails on new data.", "Symptoms: high training accuracy, low test accuracy. Causes: too complex model, too little data, training too long. Fixes: regularization (L1/L2), dropout, more data, early stopping, cross-validation.", "programming"),
  item("FACT", "Gradient descent is an optimization algorithm that iteratively reduces error by moving in the direction of steepest descent.", "Learning rate controls step size. Too high: overshoots; too low: slow. Variants: stochastic (one sample), mini-batch (small groups), Adam (adaptive). Backbone of neural network training.", "programming"),
  item("FACT", "Backpropagation computes gradients of the loss with respect to all weights in a neural network.", "Chain rule of calculus applied layer by layer. Enables efficient training by computing how much each weight contributed to the error. Combined with gradient descent to update weights.", "programming"),
  item("FACT", "An API (Application Programming Interface) lets software components communicate.", "Defines endpoints, request/response formats, authentication. REST APIs use HTTP. GraphQL uses single endpoint. RPC (gRPC) for internal services. Webhooks (callbacks) for events. Enables modular software.", "programming"),
  item("FACT", "A closure is a function that retains access to variables from its lexical scope, even when called outside that scope.", "Common in JavaScript. Enables data privacy, function factories, callbacks. Example: function returning an inner function that uses outer variables.", "programming"),
  item("FACT", "Recursion is when a function calls itself to solve smaller instances of a problem.", "Requires base case (stops recursion) and recursive case. Examples: factorial, Fibonacci, tree traversal. Risk: stack overflow if too deep. Iterative solutions often more efficient but recursion can be clearer.", "programming"),
  item("FACT", "An array stores elements in contiguous memory; a linked list stores nodes with pointers.", "Arrays: O(1) random access, O(n) insert/delete in middle. Linked lists: O(n) access, O(1) insert/delete if node known. Choice depends on use case (random access vs frequent insertion).", "programming"),
  item("FACT", "TCP (Transmission Control Protocol) provides reliable, ordered, error-checked delivery; UDP (User Datagram Protocol) is faster but unreliable.", "TCP: handshake, acknowledgments, retransmission. Used for web, email, file transfer. UDP: no guarantees, low overhead. Used for video streaming, gaming, DNS, VoIP.", "programming"),

  // ===== Philosophy (20) =====
  item("FACT", "Socrates (470-399 BCE) was a Greek philosopher who taught by asking questions (the Socratic method).", "Wrote nothing; known through Plato. Was sentenced to death by hemlock for 'corrupting youth'. Famous for: 'The unexamined life is not worth living.' Taught Plato, who taught Aristotle.", "philosophy"),
  item("FACT", "Plato's Theory of Forms posits that abstract ideals (Truth, Beauty, Justice) exist in a perfect realm, of which physical objects are imperfect copies.", "Allegory of the Cave: prisoners see shadows, not reality. True knowledge comes from reasoning about Forms, not sensory experience. Founded the Academy (~387 BCE).", "philosophy"),
  item("FACT", "Aristotle (384-322 BCE) systematized logic, ethics, politics, and science.", "Student of Plato, tutor of Alexander the Great. Founded logic (syllogisms). Ethics: virtue is the mean between extremes (courage between cowardice/recklessness). Influenced Western thought for 2000 years.", "philosophy"),
  item("FACT", "Immanuel Kant's categorical imperative states: act only on principles you'd will to be universal law.", "Deontological ethics: duty-based, not consequence-based. Treat people as ends, never merely means. 'Critique of Pure Reason' (1781) synthesized rationalism and empiricism.", "philosophy"),
  item("FACT", "Utilitarianism judges actions by their consequences: the greatest good for the greatest number.", "Jeremy Bentham (1748-1832) and John Stuart Mill (1806-1873). Bentham: maximize pleasure, minimize pain. Mill: quality of pleasure matters. Criticized for ignoring rights and justice.", "philosophy"),
  item("FACT", "René Descartes ('I think, therefore I am') founded modern Western philosophy.", 'Methodological skepticism: doubt everything. Only the doubting self is certain. Dualism: mind and body are separate substances. "I think, therefore I am" (Cogito, ergo sum).', "philosophy"),
  item("FACT", "Friedrich Nietzsche declared 'God is dead' — traditional values must be reevaluated.", "Nihilism: without God, meaning collapses. But he urged creating new values: the Übermensch (superman) who affirms life. Criticized herd mentality. Wrote 'Thus Spoke Zarathustra'.", "philosophy"),
  item("FACT", "Existentialism holds that existence precedes essence — humans create their own meaning.", "Jean-Paul Sartre, Albert Camus, Simone de Beauvoir. Radical freedom and responsibility. 'Hell is other people' (Sartre). Camus's Myth of Sisyphus: embrace the absurd.", "philosophy"),
  item("FACT", "The trolley problem is an ethical dilemma: divert a trolley to kill one instead of five.", "Most people divert. But pushing a large person off a bridge to stop it (same numbers) feels wrong. Highlights utilitarian vs deontological reasoning, the role of intention.", "philosophy"),
  item("FACT", "Logical fallacies are errors in reasoning that undermine arguments.", "Ad hominem (attack person), straw man (misrepresent), false dichotomy (two options when more exist), slippery slope, circular reasoning, appeal to authority, confirmation bias, post hoc ergo propter hoc.", "philosophy"),

  // ===== Arts & Literature (20) =====
  item("FACT", "William Shakespeare (1564-1616) wrote 39 plays and 154 sonnets.", "Tragedies: Hamlet, Macbeth, Othello, King Lear. Comedies: A Midsummer Night's Dream, Twelfth Night. Histories: Henry V, Richard III. Coined ~1700 English words. Performed at the Globe Theatre, London.", "literature"),
  item("FACT", "George Orwell's '1984' depicts a totalitarian surveillance state.", "Big Brother watches. Newspeak limits thought. Doublethink holds contradictory beliefs. Room 101 breaks resistance. Themes: propaganda, censorship, manipulation of truth. Written 1948, published 1949.", "literature"),
  item("FACT", "The Renaissance (14th-17th century) was a cultural rebirth in Europe emphasizing classical learning and humanism.", "Began in Florence, Italy. Figures: Leonardo da Vinci, Michelangelo, Raphael. Shift from medieval theology to human-centered art/science. Gutenberg's printing press (1440) spread ideas rapidly.", "art"),
  item("FACT", "Impressionism was a 19th-century art movement emphasizing light and momentary impressions.", "Claude Monet, Pierre-Auguste Renoir, Edgar Degas, Camille Pissarro. Painted outdoors (en plein air), visible brushstrokes, vibrant colors. Initially mocked, now beloved. Monet's 'Water Lilies' is iconic.", "art"),
  item("FACT", "Pablo Picasso co-founded Cubism, revolutionizing modern art.", "Cubism (with Braque) breaks objects into geometric facets, showing multiple viewpoints simultaneously. Periods: Blue, Rose, African, Cubist, Neoclassical. 'Les Demoiselles d'Avignon' (1907) and 'Guernica' (1937) are landmark works.", "art"),
  item("FACT", "Ludwig van Beethoven (1770-1827) bridged Classical and Romantic eras in music.", "9 symphonies, 32 piano sonatas, 16 string quartets. Continued composing after going deaf (~1818). Symphony No. 9 ('Ode to Joy') was the first choral symphony. revolutionary in form and emotional depth.", "music"),

  // ===== Mathematics — Advanced (35) =====
  item("FACT", "The derivative measures the instantaneous rate of change of a function.", "Geometrically: slope of the tangent line. Notation: f'(x) or dy/dx. Power rule: d/dx x^n = nx^(n-1). Product rule: (uv)' = u'v + uv'. Chain rule: d/dx f(g(x)) = f'(g(x))·g'(x).", "math"),
  item("FACT", "The integral is the area under a curve; definite integral gives net area between bounds.", "Fundamental theorem of calculus links derivatives and integrals. Power rule: ∫x^n dx = x^(n+1)/(n+1) + C. Used to find displacement from velocity, total from rate, probability in statistics.", "math"),
  item("FACT", "The natural logarithm ln(x) is the inverse of e^x, where e ≈ 2.71828 is Euler's number.", "ln(e)=1, ln(1)=0. ln(ab)=ln(a)+ln(b), ln(a/b)=ln(a)-ln(b). e^x is its own derivative. Used in compound interest, radioactive decay, population growth, normal distribution.", "math"),
  item("FACT", "A matrix is a rectangular array of numbers; matrix multiplication is row-by-column.", "If A is m×n and B is n×p, AB is m×p. Not commutative (AB≠BA). Determinant measures scaling factor of linear transformation. Used in linear algebra, graphics, ML.", "math"),
  item("FACT", "Eigenvalues and eigenvectors of a matrix are special values/vectors where Av = λv.", "Transformation A only stretches (doesn't rotate) eigenvectors by factor λ. Used in PCA (data reduction), quantum mechanics, Google PageRank, stability analysis.", "math"),
  item("FACT", "Bayes' theorem updates probabilities given new evidence: P(A|B) = P(B|A)·P(A)/P(B).", "Foundation of Bayesian inference. Prior P(A) → posterior P(A|B) after observing B. Used in spam filtering, medical testing, ML, scientific reasoning. Frequentist vs Bayesian statistics debate.", "math"),
  item("FACT", "The normal distribution (bell curve) is symmetric around the mean, described by μ (mean) and σ (standard deviation).", "68% of data within 1σ, 95% within 2σ, 99.7% within 3σ (empirical rule). Central limit theorem: sample means approach normal as sample size grows, regardless of population distribution.", "math"),
  item("FACT", "Standard deviation measures how spread out data is from the mean.", "σ = √(Σ(xᵢ-μ)²/N). Variance is σ². Low σ: data clusters near mean. High σ: data spread out. Used with mean to describe distributions, detect outliers, set confidence intervals.", "math"),
  item("FACT", "A p-value is the probability of observing results at least as extreme as the sample, assuming the null hypothesis is true.", "Common threshold p<0.05 means <5% chance of such results if null is true. Lower p → stronger evidence against null. Criticized for misuse; effect size and replication matter too.", "math"),
  item("FACT", "The Pythagorean theorem states in a right triangle, a² + b² = c², where c is the hypotenuse.", "Attributed to Pythagoras (~500 BCE), known earlier in Babylon/India. Generalizes to any dimension. Distance formula in n-D: d = √(Σ(xᵢ-yᵢ)²).", "math"),
  item("FACT", "Sine, cosine, and tangent are trigonometric ratios in right triangles.", "sin = opposite/hypotenuse, cos = adjacent/hypotenuse, tan = opposite/adjacent. sin²θ + cos²θ = 1 (Pythagorean identity). Used in waves, rotation, navigation, surveying.", "math"),
  item("FACT", "The Fibonacci sequence starts 0,1,1,2,3,5,8,13... where each term is the sum of the previous two.", "Ratio of consecutive terms approaches the golden ratio φ ≈ 1.618. Appears in nature (sunflower seeds, nautilus shells, branching). Related to the golden spiral.", "math"),
  item("FACT", "The golden ratio φ = (1+√5)/2 ≈ 1.618 appears in art, architecture, and nature.", "Defined by a/b = (a+b)/a. Rectangle with sides in golden ratio considered aesthetically pleasing. Used in Parthenon, Renaissance art. Fibonacci sequence approaches φ.", "math"),
  item("FACT", "The quadratic formula solves ax² + bx + c = 0: x = (-b ± √(b²-4ac)) / 2a.", "Discriminant b²-4ac determines roots: >0 two real, =0 one real (double), <0 two complex. Used throughout physics, engineering, optimization.", "math"),
  item("FACT", "Euler's identity e^(iπ) + 1 = 0 connects the five most important constants.", "e (natural base), i (imaginary unit), π (circle ratio), 1, 0. Called the most beautiful equation in mathematics. Links exponential, trigonometric, and algebraic realms.", "math"),

  // ===== Psychology (20) =====
  item("FACT", "Classical conditioning (Pavlov) pairs a neutral stimulus with one that triggers a response until the neutral alone does.", "Pavlov's dogs salivated to a bell after bell+food pairing. Used in advertising, phobia treatment. John Watson's 'Little Albert' experiment showed fear conditioning.", "psychology"),
  item("FACT", "Operant conditioning (Skinner) shapes behavior via reinforcement (increases) or punishment (decreases).", "Positive reinforcement: add pleasant (treat for sitting). Negative: remove unpleasant (mute alarm on seatbelt). Positive punishment: add unpleasant (spanking). Negative: remove pleasant (no phone).", "psychology"),
  item("FACT", "Confirmation bias is the tendency to seek/interpret information confirming existing beliefs.", "We notice evidence supporting us, ignore contradicting evidence. Fuels echo chambers, conspiracy theories, prejudice. Counteract by actively seeking opposing views.", "psychology"),
  item("FACT", "The Dunning-Kruger effect: incompetent people overestimate their skill; experts underestimate theirs.", "Beginners don't know what they don't know, so feel confident. As knowledge grows, awareness of gaps grows. Curve: confidence peaks early, dips, slowly rises with real competence.", "psychology"),
  item("FACT", "Maslow's hierarchy of needs: physiological → safety → belonging → esteem → self-actualization.", "Abraham Maslow (1943). Lower needs must be met before higher ones motivate. Self-actualization: fulfilling one's potential. Criticized for cultural bias (Western individualism).", "psychology"),
  item("FACT", "Memory has three stages: sensory (milliseconds), short-term/working (~20 seconds, 7±2 items), long-term (potentially lifetime).", "Sensory registers briefly. Working memory holds active info. Long-term: episodic (events), semantic (facts), procedural (skills). Forgetting curve (Ebbinghaus) shows rapid initial loss.", "psychology"),

  // ===== Business (20) =====
  item("FACT", "Porter's Five Forces analyzes industry competitiveness: rivalry, new entrants, substitutes, supplier power, buyer power.", "Michael Porter (1979). Strong forces reduce profitability. Use to decide whether to enter/exit an industry, where to compete. Complements SWOT analysis.", "business"),
  item("FACT", "SWOT analysis evaluates Strengths, Weaknesses, Opportunities, Threats.", "Internal: strengths/weaknesses (resources, capabilities). External: opportunities/threats (market, competition, regulation). Used for strategy, planning, decision-making.", "business"),
  item("FACT", "The marketing mix (4Ps) is Product, Price, Place, Promotion.", "Product: what you sell. Price: how much. Place: distribution channels. Promotion: advertising/sales. Extended to 7Ps (People, Process, Physical evidence) for services.", "business"),
  item("FACT", "Compound annual growth rate (CAGR) measures average annual growth over a period: CAGR = (End/Start)^(1/years) - 1.", "Smooths volatility. $100→$200 over 5 years = 14.9% CAGR. Used to compare investments, business growth. Doesn't reflect year-to-year variability.", "business"),

  // ===== Geography — Countries & Capitals (60) =====
  item("FACT", "Tokyo is the capital of Japan, a country of about 125 million people in East Asia.", "Japan is an archipelago of 6852 islands. World's 3rd largest economy. Known for technology, anime, sushi, Mt. Fuji, cherry blossoms. Constitutional monarchy with Emperor + Prime Minister.", "geography"),
  item("FACT", "Beijing is the capital of China, the world's most populous country until 2023 (now India).", "China: 1.4 billion people, 4th largest by area. Communist one-party state. 2nd largest economy. Great Wall, Forbidden City, Terracotta Army. Han Chinese majority, 56 ethnic groups.", "geography"),
  item("FACT", "New Delhi is the capital of India, the world's most populous country (1.43 billion as of 2023).", "India: 28 states, 8 union territories. World's largest democracy. Hinduism (80%), Islam (14%), Sikhism, Christianity, Buddhism, Jainism. 22 official languages, Hindi most spoken. Bollywood, IT, cricket.", "geography"),
  item("FACT", "Washington, D.C. is the capital of the United States of America.", "USA: 50 states, 331 million people. Federal republic. 3rd largest by area, largest economy. Independence: 1776. Constitution (1787). English majority, Spanish 2nd. Hollywood, Silicon Valley, Wall Street.", "geography"),
  item("FACT", "London is the capital of the United Kingdom (England, Scotland, Wales, Northern Ireland).", "UK: 67 million people. Constitutional monarchy (King Charles III) + parliamentary democracy. Former British Empire largest in history. Member of UN Security Council, NATO, G7. Left EU in 2020 (Brexit).", "geography"),
  item("FACT", "Paris is the capital of France, the largest country in Western Europe.", "France: 67 million people. Republic. EU founder. Known for Eiffel Tower, Louvre, cuisine, wine, fashion. French spoken in 29 countries. 75 million tourists annually (most visited country).", "geography"),
  item("FACT", "Berlin is the capital of Germany, Europe's largest economy.", "Germany: 84 million people. Federal republic of 16 states. EU founder. 4th largest economy. Known for autobahn, BMW, Mercedes, beer (Oktoberfest), philosophy, engineering. Reunified 1990 after Cold War division.", "geography"),
  item("FACT", "Moscow is the capital of Russia, the largest country by area (17 million km²).", "Russia: 144 million people across 11 time zones. Spans Europe and Asia. Rich in oil, gas, minerals. Federation. UN Security Council. Soviet Union dissolved 1991. Russian language in former Soviet states.", "geography"),
  item("FACT", "Ottawa is the capital of Canada, the second-largest country by area.", "Canada: 38 million people. Constitutional monarchy (King Charles III head of state). 10 provinces, 3 territories. Bilingual (English, French). Known for wilderness, hockey, maple syrup, politeness. G7 member.", "geography"),
  item("FACT", "Canberra is the capital of Australia (not Sydney or Melbourne).", "Australia: 26 million people. 6 states, 2 territories. Constitutional monarchy. Smallest continent, 6th largest country. Known for kangaroos, koalas, Outback, Great Barrier Reef, Sydney Opera House.", "geography"),
  item("FACT", "Riyadh is the capital of Saudi Arabia, the largest country in the Arabian Peninsula.", "Saudi Arabia: 36 million people. Absolute monarchy (House of Saud). Islam's holiest sites (Mecca, Medina) — annual Hajj pilgrimage. Oil reserves (Aramco, world's most valuable company).", "geography"),
  item("FACT", "Abu Dhabi is the capital of the United Arab Emirates (UAE).", "UAE: 10 million people, federation of 7 emirates (Abu Dhabi, Dubai, Sharjah, Ajman, Umm Al Quwain, Ras Al Khaimah, Fujairah). Oil wealth, tourism, Burj Khalifa (tallest building). Dubai is largest city.", "geography"),
  item("FACT", "Ankara is the capital of Turkey (not Istanbul).", "Turkey: 85 million people. Republic founded 1923 by Atatürk. Secular constitution with Muslim majority. Straddles Europe and Asia (Bosphorus). NATO member. Istanbul (formerly Constantinople) is largest city.", "geography"),
  item("FACT", "Rome is the capital of Italy.", "Italy: 59 million people. Republic. EU founder. Boot-shaped peninsula. Famous for Roman Empire, Renaissance, cuisine (pizza, pasta, gelato), art (Michelangelo, Da Vinci), fashion (Milan), Vatican City enclave.", "geography"),
  item("FACT", "Madrid is the capital of Spain.", "Spain: 47 million people. Constitutional monarchy (King Felipe VI). EU member. Known for flamenco, bullfighting, tapas, siesta, Sagrada Familia (Barcelona), Picasso, Cervantes (Don Quixote). Spanish spoken by 500M+ globally.", "geography"),
  item("FACT", "Cairo is the capital of Egypt, the most populous Arab country (~110 million).", "Egypt: in northeastern Africa + Sinai (Asia). Republic. Ancient civilization (pyramids, pharaohs). Nile River (lifeblood). Arabic official. Islam (90%) + Coptic Christianity. Suez Canal connects Mediterranean and Red Sea.", "geography"),
  item("FACT", "Brasília is the capital of Brazil (not Rio or São Paulo).", "Brazil: 215 million people, largest in South America. Portuguese (not Spanish) official. Amazon rainforest (60% of Amazon). Federation of 26 states. Known for Carnival, football (5 World Cups), samba, Christ the Redeemer.", "geography"),
  item("FACT", "Mexico City is the capital of Mexico.", "Mexico: 130 million people. Federal republic. 31 states + Mexico City. Spanish (92%) + 68 indigenous languages. Aztec and Mayan heritage. Known for tacos, mariachi, Day of the Dead, tequila. NAFTA/USMCA partner. Drug cartel issues.", "geography"),
  item("FACT", "Seoul is the capital of South Korea (Republic of Korea).", "South Korea: 52 million people. Republic. K-pop, K-dramas, Samsung, LG, Hyundai. 4th largest in Asia. Korean War (1950-53) ended in armistice, no peace treaty. One of world's most wired countries. High-tech economy.", "geography"),
  item("FACT", "Buenos Aires is the capital of Argentina.", "Argentina: 46 million people. 8th largest country by area. Spanish (with Italian influence). Known for tango, football (Messi, Maradona), beef, Andes mountains, Patagonia, pampas. Recurring economic crises. Falklands War (1982) with UK.", "geography"),
  item("FACT", "Jakarta is the capital of Indonesia (moving to Nusantara).", "Indonesia: 277 million people (4th most populous). Archipelago of 17,000+ islands. World's largest Muslim population. Bahasa Indonesia official. Java is most populous island. Known for Bali, Komodo dragons, temples (Borobudur).", "geography"),
  item("FACT", "Bangkok is the capital of Thailand.", "Thailand: 70 million people. Constitutional monarchy (King Vajiralongkorn). Never colonized. Buddhism (95%). Known for temples, Pad Thai, Muay Thai, elephants, beaches (Phuket). Tourism major industry.", "geography"),
  item("FACT", "Hanoi is the capital of Vietnam.", "Vietnam: 98 million people. Socialist republic. Vietnam War (1955-75) ended with reunification. Fast-growing economy. Known for phở, bánh mì, coffee, Ha Long Bay, Mekong Delta, motorbikes. Young population.", "geography"),
  item("FACT", "Manila is the capital of the Philippines.", "Philippines: 115 million people. Archipelago of 7641 islands. Republic. Filipino + English official. Catholic majority (Spanish/American colonial influence). Known for beaches (Boracay), boxing (Pacquiao), OFWs (overseas workers).", "geography"),
  item("FACT", "Nairobi is the capital of Kenya.", "Kenya: 55 million people. Republic in East Africa. Swahili + English official. Maasai culture. Known for safaris (Maasai Mara), Mt. Kenya, runners (long-distance). M-Pesa (mobile money) pioneered here.", "geography"),
  item("FACT", "Lagos is the largest city in Nigeria; Abuja is the capital.", "Nigeria: 220 million people (most populous in Africa). Federal republic. 250+ ethnic groups (Hausa, Yoruba, Igbo). English official. Oil-rich. Nollywood (2nd largest film industry by volume). Known for Afrobeats (Burna Boy, Wizkid).", "geography"),
  item("FACT", "Pretoria is the administrative capital of South Africa (Cape Town legislative, Bloemfontein judicial).", "South Africa: 60 million people. 3 capitals. 11 official languages. Republic. Apartheid ended 1994 (Mandela first black president). Rich in minerals (gold, platinum). Known for safaris, Table Mountain, Nelson Mandela.", "geography"),
  item("FACT", "Athens is the capital of Greece.", "Greece: 10.4 million people. EU + NATO. Birthplace of democracy, Western philosophy (Socrates, Plato, Aristotle), Olympic Games (ancient). Known for Acropolis (Parthenon), Santorini, Mediterranean cuisine, olive oil. Debt crisis 2009-2018.", "geography"),
  item("FACT", "Lisbon is the capital of Portugal.", "Portugal: 10.3 million people. EU member. Republic. Portuguese spoken by 250M+ globally (Brazil, Angola, Mozambique). Known for Age of Discovery (Vasco da Gama, Magellan), fado music, port wine, cork, codfish (bacalhau).", "geography"),
  item("FACT", "Amsterdam is the capital of the Netherlands; The Hague is the seat of government.", "Netherlands: 17.5 million people. Constitutional monarchy (King Willem-Alexander). EU founder. Below sea level (Dutch engineering, dikes, polders). Known for tulips, windmills, canals, cheese (Gouda, Edam), bicycles, art (Rembrandt, Vermeer, Van Gogh).", "geography"),
  item("FACT", "Stockholm is the capital of Sweden.", "Sweden: 10.5 million people. Constitutional monarchy. EU member. Neutral (not NATO until 2024). Known for IKEA, Volvo, ABBA, Spotify, Nobel Prize. High taxes, strong welfare state. Swedish is official.", "geography"),
  item("FACT", "Oslo is the capital of Norway.", "Norway: 5.4 million people. Constitutional monarchy. Not EU. Oil-rich (sovereign wealth fund ~$1.5T). Known for fjords, Vikings, Northern Lights, skiing, salmon. High standard of living. NATO member.", "geography"),
  item("FACT", "Copenhagen is the capital of Denmark.", "Denmark: 5.9 million people. Constitutional monarchy. EU member. Known for LEGO, Hans Christian Andersen, cycling culture, design (Arne Jacobsen), New Nordic cuisine (Noma). Greenland + Faroe Islands are territories.", "geography"),
  item("FACT", "Helsinki is the capital of Finland.", "Finland: 5.5 million people. Republic. EU member. Finnish + Swedish official. Known for Nokia, saunas, education system (top in PISA), Lapland (Santa Claus), Northern Lights, lakes (188,000).", "geography"),
  item("FACT", "Warsaw is the capital of Poland.", "Poland: 38 million people. EU + NATO. Republic. Catholic (90%). Rebuilt after WWII devastation. Known for Copernicus, Chopin, Marie Curie, John Paul II, Solidarity movement (ended communism 1989). Pierogi, kielbasa.", "geography"),
  item("FACT", "Kyiv (Kiev) is the capital of Ukraine.", "Ukraine: 41 million people. Republic. Former Soviet. Russian invasion 2022 ongoing. Known for Chernobyl (1986), wheat exports, Orthodox Christianity, vyshyvanka embroidery. EU candidate 2022.", "geography"),
  item("FACT", "Tehran is the capital of Iran.", "Iran: 88 million people. Islamic Republic (1979 revolution). Persian (Farsi) official. Shia Islam (90%). Oil, gas reserves. Known for Persian culture (Rumi, Hafez), carpets, caviar, Persepolis. Sanctions over nuclear program.", "geography"),
  item("FACT", "Baghdad is the capital of Iraq.", "Iraq: 44 million people. Republic. Arabic + Kurdish. Shia (60%) + Sunni (40%) + Kurds (north). Tigris + Euphrates rivers. Cradle of civilization (Mesopotamia, Babylon). 2003 US invasion, ongoing instability.", "geography"),
  item("FACT", "Riyadh is the capital of Saudi Arabia; Mecca and Medina are Islam's holiest cities.", "Saudi Arabia: 36 million. Two holy mosques (Mecca — Kaaba, annual Hajj; Medina — Prophet's Mosque). Wahhabi Islam. Oil (Aramco). Vision 2030 modernization by Crown Prince MBS.", "geography"),
  item("FACT", "Islamabad is the capital of Pakistan.", "Pakistan: 240 million people (5th most populous). Islamic republic. Urdu + English. 95% Muslim. Created 1947 partition of British India. Nuclear power. Known for cricket, mangoes, K2 (2nd highest mountain), Indus Valley Civilization (Mohenjo-daro).", "geography"),
  item("FACT", "Dhaka is the capital of Bangladesh.", "Bangladesh: 170 million people. Republic. Bengali official. Muslim (90%) + Hindu. Former East Pakistan (independent 1971). Ganges-Brahmaputra delta — flooding, fertile. Garment industry (world's 2nd largest exporter).", "geography"),
  item("FACT", "Kuala Lumpur is the capital of Malaysia.", "Malaysia: 34 million people. Constitutional monarchy (rotating king). Malay, Chinese, Indian ethnic groups. Malay (Bahasa Malaysia) + English + Chinese + Tamil. Muslim majority. Petronas Towers (twin towers). Rainforests, orangutans (Borneo).", "geography"),
  item("FACT", "Singapore is a city-state and island country at the tip of Malaysia.", "Singapore: 5.7 million people. Republic. Multiracial (Chinese 74%, Malay, Indian). English, Malay, Mandarin, Tamil all official. Financial hub, port. Known for cleanliness, hawker food, Marina Bay Sands, strict laws.", "geography"),
  item("FACT", "Wellington is the capital of New Zealand; Auckland is the largest city.", "New Zealand: 5.1 million people. Constitutional monarchy. Two main islands. Māori indigenous people (treaty of Waitangi 1840). Known for rugby (All Blacks), Lord of the Rings filming, kiwi bird, sheep, stunning landscapes.", "geography"),
  item("FACT", "Dublin is the capital of Ireland.", "Ireland (Republic of): 5.1 million people. EU member. English + Irish (Gaelic). Catholic tradition. Known for Guinness, St. Patrick's Day, literature (Joyce, Yeats, Beckett), Celtic music, Cliffs of Moher. Northern Ireland is UK.", "geography"),
  item("FACT", "Vienna is the capital of Austria.", "Austria: 9 million people. EU member. Republic. German official. Known for classical music (Mozart, Strauss, Schubert), Vienna Boys Choir, Schnitzel, Sachertorte, Alps skiing, Habsburg Empire, Freud (psychoanalysis).", "geography"),
  item("FACT", "Prague is the capital of the Czech Republic.", "Czech Republic: 10.5 million people. EU + NATO. Republic. Czech official. Known for Prague Castle, Charles Bridge, beer (highest per capita consumption), Kafka, Dvořák, Smetana. Velvet Divorce with Slovakia 1993.", "geography"),
  item("FACT", "Budapest is the capital of Hungary.", "Hungary: 9.6 million people. EU + NATO. Republic. Hungarian (not Indo-European). Known for Buda + Pest (two cities united), Parliament, thermal baths, goulash, paprika, Rubik's Cube, Béla Bartók.", "geography"),
  item("FACT", "Bucharest is the capital of Romania.", "Romania: 19 million people. EU + NATO. Republic. Romanian (Latin-based). Orthodox Christianity. Known for Carpathian Mountains, Dracula (Transylvania, Bran Castle), painted monasteries, gymnastics (Nadia Comăneci).", "geography"),
  item("FACT", "Ankara is the capital of Turkey; Istanbul spans Europe and Asia via the Bosphorus Strait.", "Turkey: 85 million. NATO member. EU candidate (stalled). Secular constitution. Istanbul (formerly Constantinople, capital of Byzantine + Ottoman empires) is largest city. Turkish language, Islam majority.", "geography"),
  item("FACT", "Abuja is the capital of Nigeria; Lagos is the largest city.", "Nigeria: 220M people. Federal republic. English + Hausa, Yoruba, Igbo. Africa's largest economy (oil). Nollywood film industry. Afrobeats global phenomenon (Burna Boy, Wizkid, Davido).", "geography"),
  item("FACT", "Accra is the capital of Ghana.", "Ghana: 34 million people. Republic. English official. First sub-Saharan African country to gain independence (1957, Nkrumah). Known for cocoa, gold, Kente cloth, Ashanti Empire heritage. Stable democracy.", "geography"),
  item("FACT", "Addis Ababa is the capital of Ethiopia.", "Ethiopia: 120 million people. Federal republic. Never colonized (except brief Italian occupation 1936-41). Amharic official. Coffee origin. African Union HQ. Ancient Christian civilization (Aksum, Lalibela rock churches).", "geography"),
  item("FACT", "Nairobi is the capital of Kenya; the equator passes through Kenya.", "Kenya: 55 million people. Republic. Swahili + English. Known for Maasai Mara (Great Migration), Mt. Kenya, long-distance runners (Kalenjin tribe). M-Pesa (mobile money) pioneered here. UN Environment Programme HQ.", "geography"),
  item("FACT", "Havana is the capital of Cuba.", "Cuba: 11.3 million people. Communist one-party state since 1959 revolution (Castro). Spanish official. Known for cigars, rum, salsa music, vintage American cars, classic colonial architecture. US embargo since 1960. Medical internationalism.", "geography"),
  item("FACT", "Lima is the capital of Peru.", "Peru: 34 million people. Republic. Spanish + Quechua + Aymara. Known for Inca Empire (Machu Picchu), Nazca Lines, Amazon rainforest (60% of Peru), Andes mountains, ceviche, llamas, alpacas.", "geography"),
  item("FACT", "Santiago is the capital of Chile.", "Chile: 19.5 million people. Republic. Long, narrow country along Pacific. Spanish official. Known for Andes, Atacama Desert (driest), Patagonia, wine, copper (largest producer), Pablo Neruda, Easter Island (Moai statues).", "geography"),
  item("FACT", "Bogotá is the capital of Colombia.", "Colombia: 52 million people. Republic. Spanish official. 2nd most biodiverse country. Known for coffee (world's 3rd largest producer), emeralds, Gabriel García Márquez (magical realism), Shakira, salsa, cumbia, Amazon rainforest.", "geography"),
  item("FACT", "Caracas is the capital of Venezuela.", "Venezuela: 28 million people. Federal republic. Spanish official. Oil reserves (largest in world). Bolívar currency (hyperinflation crisis). Known for Angel Falls (world's tallest), beauty pageants, arepas, Simón Bolívar (liberator).", "geography"),
  item("FACT", "Bridgetown is the capital of Barbados.", "Barbados: 288,000 people. Parliamentary republic (became republic 2021, removed British monarch as head of state). Easternmost Caribbean island. English + Bajan. Known for rum, Rihanna, cricket, pink sand beaches.", "geography"),
  item("FACT", "Kingston is the capital of Jamaica.", "Jamaica: 2.8 million people. Constitutional monarchy (King Charles III head of state). English + Jamaican Patois. Known for reggae (Bob Marley), Usain Bolt, Blue Mountain coffee, jerk chicken, Rastafarianism.", "geography"),

  // ===== History — More (25) =====
  item("FACT", "The Roman Empire (27 BCE - 476 CE Western) was one of history's largest, spanning Europe, North Africa, Western Asia.", "At its peak (117 CE under Trajan): 5M km², 50-90M people (20% of world). Latin → Romance languages. Roman law, engineering (aqueducts, roads), Christianity adopted (313 CE). Eastern half (Byzantine) lasted to 1453.", "history"),
  item("FACT", "The Byzantine Empire (330-1453) was the Eastern Roman Empire centered on Constantinople.", "Capital Constantinople (modern Istanbul). Greek-speaking, Orthodox Christian. Preserved Greco-Roman knowledge through Middle Ages. Fell to Ottoman Turks in 1453. Justinian's Code shaped European law. Hagia Sophia its iconic church/mosque.", "history"),
  item("FACT", "The Mongol Empire (1206-1368) was the largest contiguous land empire ever.", "Founded by Genghis Khan. At its peak: 24M km² (16% of Earth's land), ~100M people. Stretched from Korea to Hungary. Pax Mongolica enabled Silk Road trade. Split into 4 khanates. Known for horse archers, religious tolerance, brutal conquests.", "history"),
  item("FACT", "The Islamic Golden Age (8th-14th century) saw major advances in science, math, medicine, philosophy.", "Centered in Baghdad (House of Wisdom). Scholars translated Greek/Persian/Indian texts. Al-Khwarizmi (algebra), Ibn Sina (Avicenna — medicine), Al-Razi (chemistry), Ibn Rushd (Averroes — philosophy). Saved classical knowledge for Europe.", "history"),
  item("FACT", "The Black Death (1347-1351) killed 30-60% of Europe's population.", "Bubonic plague from Central Asia via Silk Road, spread by fleas on rats. Devastated economy, weakened feudalism, spurred labor-saving inventions. Recurred for centuries. Last major European outbreak: Marseille 1720.", "history"),
  item("FACT", "The Age of Discovery (15th-17th century) saw European powers explore and colonize globally.", "Portugal (Henry the Navigator, Vasco da Gama to India 1498), Spain (Columbus 1492, Magellan's circumnavigation 1519-22). Columbian Exchange transferred crops, animals, diseases. Devastated indigenous populations. Led to colonial empires.", "history"),
  item("FACT", "The Industrial Revolution (1760-1840) transformed economies from agrarian to industrial.", "Began in Britain. Steam engine (Watt), textile machinery, iron, coal. Urbanization, factory system, railways. Raised living standards long-term but caused harsh early conditions (child labor, slums). Spread to Europe, America, Japan.", "history"),
  item("FACT", "The French Revolution (1789-1799) overthrew the monarchy, established a republic, and ended with Napoleon's rise.", "Causes: financial crisis, inequality, Enlightenment ideas. Storming of Bastille (July 14, 1789). Reign of Terror (Robespierre). Napoleon crowned himself emperor 1804, defeated 1815 (Waterloo). 'Liberty, equality, fraternity.'", "history"),
  item("FACT", "The American Revolution (1775-1783) established the United States as independent from Britain.", "13 colonies declared independence July 4, 1776. George Washington led Continental Army. French aid crucial. Constitution (1787), Bill of Rights (1791). Established federal democratic republic. Inspired other revolutions.", "history"),
  item("FACT", "World War I (1914-1918) killed ~20 million people and reshaped Europe.", "Causes: nationalism, alliances, assassination of Archduke Franz Ferdinand. Central Powers vs Allies. Trench warfare, machine guns, poison gas, tanks. Treaty of Versailles (1919) punished Germany, sowing seeds of WWII. Russian Revolution 1917.", "history"),
  item("FACT", "World War II (1939-1945) killed 70-85 million; deadliest conflict in history.", "Axis (Germany, Italy, Japan) vs Allies (UK, USSR, USA, France, China). Holocaust killed 6M Jews. Atomic bombs on Hiroshima + Nagasaki (Aug 1945). Ended European colonial empires. Led to UN, Cold War, decolonization.", "history"),
  item("FACT", "The Cold War (1947-1991) was ideological conflict between USA (capitalism) and USSR (communism).", "Never direct war between superpowers, but proxy wars (Korea, Vietnam, Afghanistan). Nuclear arms race, space race. NATO vs Warsaw Pact. Berlin Wall (1961-1989). Ended with Soviet collapse 1991.", "history"),
  item("FACT", "The Berlin Wall divided East and West Berlin from 1961 to 1989.", "Built by East Germany to stop citizens fleeing to the West. 155 km long, ~140 deaths trying to cross. Fall on Nov 9, 1989 triggered by mass protests. Symbol of Cold War division. German reunification Oct 3, 1990.", "history"),
  item("FACT", "The Apollo 11 mission landed humans on the Moon on July 20, 1969.", "Neil Armstrong and Buzz Aldrin walked on the Moon; Michael Collins orbited. 'That's one small step for [a] man, one giant leap for mankind.' Won the space race for the USA. 12 men have walked on the Moon (1969-1972).", "history"),
  item("FACT", "Mahatma Gandhi (1869-1948) led India's nonviolent independence movement against British rule.", "Trained as a lawyer in London. Civil disobedience, Salt March (1930), Quit India (1942). Inspired Martin Luther King Jr., Mandela. Assassinated by a Hindu nationalist. India independent Aug 15, 1947; partition created Pakistan.", "history"),
  item("FACT", "Nelson Mandela (1918-2013) led South Africa's anti-apartheid movement and became its first black president (1994-1999).", "Imprisoned 27 years (1962-1990). African National Congress leader. Won Nobel Peace Prize 1993 (with de Klerk). His presidency began democratic, multiracial South Africa. 'It always seems impossible until it's done.'", "history"),
  item("FACT", "The Magna Carta (1215) limited the English king's power and influenced constitutional government.", "King John forced by barons to sign at Runnymede. Established that even the king is subject to law. Right to fair trial, no taxation without representation. Inspired US Constitution, UN Declaration of Human Rights.", "history"),
  item("FACT", "The printing press, invented by Johannes Gutenberg around 1440, revolutionized information spread.", "Movable type enabled mass book production. Bible (1455) was first major printed book. Reduced cost of books, increased literacy, fueled Reformation, Renaissance, Scientific Revolution. One of history's most influential inventions.", "history"),
  item("FACT", "The September 11, 2001 attacks killed 2,977 people in the USA, leading to the War on Terror.", "Al-Qaeda hijacked 4 planes; 2 hit World Trade Center (NYC), 1 Pentagon, 1 crashed in Pennsylvania. Led to US wars in Afghanistan (2001-2021) and Iraq (2003-2011). Created DHS, TSA, expanded surveillance.", "history"),
  item("FACT", "The COVID-19 pandemic (2020-2023) killed over 7 million officially (likely 18M+ excess).", "Caused by SARS-CoV-2, emerged Wuhan, China late 2019. WHO declared pandemic March 2020. Lockdowns, masks, vaccines (mRNA — Pfizer, Moderna) developed in record time. Disrupted global economy, accelerated remote work.", "history"),

  // ===== Current / Reference (25) =====
  item("FACT", "The United Nations (UN) has 193 member states and works for peace, human rights, and development.", "Founded 1945 after WWII. HQ New York. Security Council (5 permanent veto powers: USA, UK, France, Russia, China). Agencies: WHO, UNESCO, UNICEF, UNHCR. Sustainable Development Goals (17 SDGs by 2030).", "reference"),
  item("FACT", "The European Union (EU) is a political-economic union of 27 European member states.", "Founded 1993 (Maastricht Treaty). Euro currency (20 countries). Single market: free movement of goods, services, capital, people. Parliament (Strasbourg), Commission (Brussels). UK left 2020 (Brexit).", "reference"),
  item("FACT", "NATO (North Atlantic Treaty Organization) is a 32-member military alliance formed in 1949.", "Collective defense: attack on one is attack on all (Article 5). HQ Brussels. Founded to counter Soviet threat. After Cold War, expanded east. Finland joined 2023 (after Russia's invasion of Ukraine), Sweden 2024.", "reference"),
  item("FACT", "The World Health Organization (WHO) is the UN's health agency, founded 1948.", "HQ Geneva. Coordinates international health responses, disease outbreaks, vaccines. Declared COVID-19 a pandemic March 2020. Criticized for political pressures, slow early COVID response. 194 member states.", "reference"),
  item("FACT", "The World Bank provides loans to developing countries for capital programs.", "Founded 1944 (Bretton Woods). HQ Washington, D.C. Includes IBRD + IDA. 189 members. Aims to reduce poverty, support development. Sister organization: IMF (monetary cooperation, financial stability). Both Bretton Woods institutions.", "reference"),
  item("FACT", "The world's largest religions by adherents are Christianity (~2.4 billion), Islam (~1.9 billion), Hinduism (~1.2 billion), Buddhism (~500 million).", "Christianity: largest in Americas, Europe, sub-Saharan Africa. Islam: Middle East, North Africa, South/Southeast Asia (fastest growing). Hinduism: mostly India. Buddhism: East/Southeast Asia. Judaism: ~15M, Israel + diaspora.", "reference"),
  item("FACT", "The most spoken languages by native speakers are Mandarin Chinese (~920M), Spanish (~475M), English (~375M), Hindi (~345M), Bengali (~230M).", "By total speakers (including second language): English ~1.5B, Mandarin ~1.1B, Hindi ~600M, Spanish ~550M, French ~300M. English is the global lingua franca of business, science, internet.", "reference"),
  item("FACT", "The US dollar is the world's primary reserve currency; the euro is second.", "~60% of global reserves are USD, ~20% EUR, ~6% JPY, ~5% GBP, ~3% RMB. Petrodollar system since 1970s. SWIFT system for international transfers. China promotes yuan internationalization.", "reference"),
  item("FACT", "The metric system (SI units) is used by every country except USA, Liberia, and Myanmar.", "Base units: meter (length), kilogram (mass), second (time), ampere (current), kelvin (temp), mole (amount), candela (luminosity). Decimal-based. USA uses customary units (feet, pounds, Fahrenheit).", "reference"),
  item("FACT", "Earth has 24 time zones, each roughly 15° of longitude wide (1 hour apart).", "International Date Line (~180°) — crossing east subtracts a day, west adds a day. Some zones offset by 30/45 minutes (India UTC+5:30, Nepal UTC+5:45). Daylight saving shifts clocks in summer (not all countries).", "reference"),

  // ===== Nature & Environment (20) =====
  item("FACT", "Earth's atmosphere is 78% nitrogen, 21% oxygen, 0.9% argon, 0.04% carbon dioxide (rising).", "CO2 was 280 ppm pre-industrial, now ~420 ppm (2023), causing climate change. Oxygen produced by photosynthesis. Ozone layer (stratosphere) protects from UV. Tropospheric ozone is pollution.", "environment"),
  item("FACT", "Plate tectonics explains Earth's crust as moving plates that cause earthquakes, volcanoes, and mountain building.", "Earth's lithosphere: 7 major + several minor plates. Divergent (mid-Atlantic ridge), convergent (Himalayas, Andes), transform (San Andreas) boundaries. Subduction recycles crust. Continental drift proposed by Wegener (1912).", "environment"),
  item("FACT", "Earth is approximately 4.54 billion years old, determined by radiometric dating of meteorites.", "Geological eons: Hadean, Archean, Proterozoic (together 'Precambrian', 88% of time), Phanerozoic (visible life: Paleozoic, Mesozoic, Cenozoic). Life appeared ~3.5-4 billion years ago; multicellular ~600M years ago.", "environment"),
  item("FACT", "The greenhouse effect traps heat: CO2, methane, water vapor absorb infrared radiation.", "Natural greenhouse effect keeps Earth ~33°C warmer than it would be (avg 15°C vs -18°C). Enhanced by human emissions: CO2 from fossil fuels, methane from agriculture. Causes global warming, climate change.", "environment"),
  item("FACT", "The ozone layer in the stratosphere absorbs harmful ultraviolet (UV) radiation from the Sun.", "Discovered hole over Antarctica (1985). Montreal Protocol (1987) phased out CFCs (refrigerants). Ozone layer recovering, expected to heal by 2060. Success story of international environmental cooperation.", "environment"),
  item("FACT", "Deforestation, especially in the Amazon, threatens biodiversity and accelerates climate change.", "Forests absorb CO2, regulate water, host biodiversity. Amazon (5.5M km²) stores ~76 billion tonnes carbon. Loses ~10,000 km²/year to logging, ranching, agriculture. Reforestation, sustainable practices are solutions.", "environment"),
  item("FACT", "Plastic pollution contaminates oceans, with ~8 million tonnes added yearly.", "Microplastics enter food chain. Great Pacific Garbage Patch (~1.6M km²). harms marine life (turtles eat plastic bags thinking jellyfish). 9% of plastic recycled. Solutions: reduce single-use, biodegradable alternatives, circular economy.", "environment"),

  // ===== Practical / How-To (25) =====
  item("FACT", "To hard-boil an egg: place in cold water, bring to boil, cook 9-12 minutes, then cool in ice water.", "6 min: soft runny yolk. 8 min: jammy. 10 min: firm but creamy. 12+ min: chalky yolk. Ice water stops cooking and makes peeling easier. Older eggs peel more easily than fresh.", "cooking"),
  item("FACT", "To cook white rice: rinse, use 1:1.5 to 1:2 rice-to-water ratio, simmer covered 15-20 minutes, rest 10 minutes off heat.", "Long grain: 1:1.5. Short/sushi: 1:1.1. Brown rice: 1:2, 40-45 min. Don't lift lid while cooking. Fluff with fork. 1 cup raw → ~3 cups cooked. Rice cooker automates this.", "cooking"),
  item("FACT", "To make coffee: 2 tablespoons ground coffee per 6 oz (180 ml) water; brew 4-5 minutes for French press, ~5 min for pour-over.", "Methods: drip (automatic), French press (full immersion), pour-over (V60, Chemex), espresso (high pressure), AeroPress, cold brew (12-24h, smoother). Caffeine: ~95 mg per cup (arabica less than robusta).", "cooking"),
  item("FACT", "To perform CPR on an adult: push 2 inches deep at 100-120 compressions per minute in the center of the chest.", "Allow full chest recoil. 30 compressions : 2 rescue breaths. Use the beat of 'Stayin' Alive' (103 BPM). Use AED as soon as available. Continue until help arrives, person recovers, or you're exhausted.", "first-aid"),
  item("FACT", "To stop bleeding: apply firm direct pressure with a clean cloth for 5-15 minutes, elevate the wound if possible.", "Don't remove a deeply embedded object (could worsen bleeding). For severe bleeding: tourniquet above the wound (note time applied). Seek medical help if bleeding doesn't stop, is arterial (spurting), or wound is deep/large.", "first-aid"),
  item("FACT", "To treat a minor burn: cool under running water for 10-20 minutes, don't apply ice or butter.", "First degree (red, painful). Second degree (blisters). Third degree (white/charred, may not hurt — nerve damage). Don't pop blisters. Cover with clean dry dressing. Seek help for large, deep, face/hand/genital, or chemical/electrical burns.", "first-aid"),
  item("FACT", "To change a car tire: park on flat ground, engage parking brake, loosen lug nuts slightly, jack up, remove nuts, replace tire, hand-tighten nuts, lower, fully tighten in star pattern.", "Spare tires are temporary — drive under 50 mph, replace within 50-70 miles. Check tire pressure monthly (spare included). Rotate tires every 5,000-8,000 miles for even wear.", "automotive"),
  item("FACT", "To save money: track spending, create a budget (50/30/20 rule: needs/wants/savings), build 3-6 months emergency fund, pay off high-interest debt first, invest early for compound growth.", "Pay yourself first (automate savings). 401(k) match is free money. Index funds (S&P 500) average ~7-10% annual long-term returns. Avoid lifestyle inflation. Save 15-20% of income for retirement.", "finance"),
  item("FACT", "To learn any skill: practice consistently (daily if possible), use deliberate practice (focus on weaknesses), get feedback, break it into smaller parts, teach others.", "10,000 hour rule (Ericsson) — expertise takes ~10,000 hours of deliberate practice. Spaced repetition for memorization (Anki). Pomodoro technique (25 min work + 5 min break) for focus.", "learning"),
  item("FACT", "To meditate: sit comfortably, close eyes, focus on your breath, when mind wanders (it will), gently return attention to breath.", "Start 5-10 min daily. Types: mindfulness, loving-kindness, body scan, transcendental (mantra). Benefits: reduced stress, better focus, emotional regulation. Apps: Headspace, Calm, Insight Timer.", "wellness"),
];

export async function seedGeneralKnowledgeV2(tenantId: string, applicationId: string): Promise<{ sourceId: string; itemCount: number }> {
  const { db } = await import("@/lib/db");
  const { buildTermVector, serializeVector } = await import("./vectors");

  // Find or create the V2 source
  let source = await db.knowledgeSource.findFirst({
    where: { tenantId, title: GENERAL_KNOWLEDGE_SOURCE_V2.title },
  });
  if (!source) {
    source = await db.knowledgeSource.create({
      data: {
        tenantId,
        sourceType: GENERAL_KNOWLEDGE_SOURCE_V2.sourceType,
        title: GENERAL_KNOWLEDGE_SOURCE_V2.title,
        author: GENERAL_KNOWLEDGE_SOURCE_V2.author,
        trustLevel: GENERAL_KNOWLEDGE_SOURCE_V2.trustLevel,
        verificationStatus: GENERAL_KNOWLEDGE_SOURCE_V2.verificationStatus,
        dataClassification: GENERAL_KNOWLEDGE_SOURCE_V2.dataClassification,
      },
    });
  }

  let itemCount = 0;
  for (const k of GENERAL_KNOWLEDGE_BASE_V2) {
    // Skip if already exists for this source (idempotent)
    const existing = await db.knowledgeItem.findFirst({
      where: { tenantId, sourceId: source.id, claim: k.claim },
    });
    if (existing) continue;

    await db.knowledgeItem.create({
      data: {
        tenantId,
        applicationId,
        sourceId: source.id,
        type: k.type,
        scope: k.scope ?? "APPLICATION",
        claim: k.claim,
        content: k.content,
        contentVector: serializeVector(buildTermVector(k.claim + " " + k.content)),
        status: "ACTIVE",
        confidence: 0.85,
        validFrom: k.validFrom ?? new Date(),
        refreshSchedule: "manual",
        lastRefreshedAt: new Date(),
      },
    });
    itemCount++;
  }

  return { sourceId: source.id, itemCount };
}
